// Auto-generated from rAthena nodynamicnpc.txt.
// Re-generate with: python3 scripts/tools/import_rathena.py

registerMapFlag(
    { map: "1@mist", flag: "nodynamicnpc" },
    { map: "1@pump", flag: "nodynamicnpc" },
    { map: "2@pump", flag: "nodynamicnpc" },
    { map: "1@cash", flag: "nodynamicnpc" },
    { map: "1@ma_h", flag: "nodynamicnpc" },
    { map: "1@ma_c", flag: "nodynamicnpc" },
    { map: "1@ma_b", flag: "nodynamicnpc" },
    { map: "1@lhz", flag: "nodynamicnpc" },
    { map: "1@gl_k", flag: "nodynamicnpc" },
    { map: "2@gl_k", flag: "nodynamicnpc" },
    { map: "1@ecl", flag: "nodynamicnpc" },
    { map: "1@sara", flag: "nodynamicnpc" },
    { map: "1@gef", flag: "nodynamicnpc" },
    { map: "1@gef_in", flag: "nodynamicnpc" },
    { map: "1@ge_st", flag: "nodynamicnpc" },
    { map: "1@xm_d", flag: "nodynamicnpc" },
    { map: "1@face", flag: "nodynamicnpc" },
    { map: "1@spa", flag: "nodynamicnpc" },
    { map: "1@tnm1", flag: "nodynamicnpc" },
    { map: "1@tnm2", flag: "nodynamicnpc" },
    { map: "1@tnm3", flag: "nodynamicnpc" },
    { map: "1@air1", flag: "nodynamicnpc" },
    { map: "1@air2", flag: "nodynamicnpc" },
    { map: "1@glast", flag: "nodynamicnpc" },
    { map: "1@def01", flag: "nodynamicnpc" },
    { map: "1@def02", flag: "nodynamicnpc" },
    { map: "1@jtb", flag: "nodynamicnpc" },
    { map: "1@dth1", flag: "nodynamicnpc" },
    { map: "1@dth2", flag: "nodynamicnpc" },
    { map: "1@dth3", flag: "nodynamicnpc" },
    { map: "1@rev", flag: "nodynamicnpc" },
    { map: "1@eom", flag: "nodynamicnpc" },
    { map: "1@lab", flag: "nodynamicnpc" },
    { map: "1@uns", flag: "nodynamicnpc" },
    { map: "1@mcd", flag: "nodynamicnpc" },
    { map: "2@mir", flag: "nodynamicnpc" },
    { map: "1@mir", flag: "nodynamicnpc" },
    { map: "1@sthb", flag: "nodynamicnpc" },
    { map: "1@sthc", flag: "nodynamicnpc" },
    { map: "1@sthd", flag: "nodynamicnpc" },
    { map: "1@swat", flag: "nodynamicnpc" },
    { map: "1@slw", flag: "nodynamicnpc" },
    { map: "1@infi", flag: "nodynamicnpc" },
    { map: "1@rgsr", flag: "nodynamicnpc" },
    { map: "1@os_b", flag: "nodynamicnpc" },
    { map: "1@os_a", flag: "nodynamicnpc" },
    { map: "1@cor", flag: "nodynamicnpc" },
    { map: "1@pop1", flag: "nodynamicnpc" },
    { map: "1@pop2", flag: "nodynamicnpc" },
    { map: "1@pop3", flag: "nodynamicnpc" },
    { map: "1@md_pay", flag: "nodynamicnpc" },
    { map: "1@md_gef", flag: "nodynamicnpc" },
    { map: "1@begi", flag: "nodynamicnpc" },
);
