// Auto-generated from rAthena nosave.txt.
// Re-generate with: python3 scripts/tools/import_rathena.py

registerMapFlag(
    { map: "job3_arch01", flag: "nosave", value: "SavePoint" },
    { map: "job3_arch02", flag: "nosave", value: "SavePoint" },
    { map: "job3_arch03", flag: "nosave", value: "SavePoint" },
    { map: "job3_guil01", flag: "nosave", value: "SavePoint" },
    { map: "job3_guil02", flag: "nosave", value: "SavePoint" },
    { map: "job3_guil03", flag: "nosave", value: "SavePoint" },
    { map: "job3_rang01", flag: "nosave", value: "SavePoint" },
    { map: "job3_rang02", flag: "nosave", value: "SavePoint" },
    { map: "job3_rune01", flag: "nosave", value: "SavePoint" },
    { map: "job3_rune02", flag: "nosave", value: "SavePoint" },
    { map: "job3_rune03", flag: "nosave", value: "SavePoint" },
    { map: "job3_war01", flag: "nosave", value: "SavePoint" },
    { map: "job3_war02", flag: "nosave", value: "SavePoint" },
    { map: "job3_gen01", flag: "nosave", value: "SavePoint" },
    { map: "job3_sha01", flag: "nosave", value: "SavePoint" },
    { map: "job_ko", flag: "nosave", value: "SavePoint" },
    { map: "job_gun", flag: "nosave", value: "SavePoint" },
    { map: "gld_dun01_2", flag: "nosave", value: "SavePoint" },
    { map: "gld_dun02_2", flag: "nosave", value: "SavePoint" },
    { map: "gld_dun03_2", flag: "nosave", value: "SavePoint" },
    { map: "gld_dun04_2", flag: "nosave", value: "SavePoint" },
    { map: "gld2_ald", flag: "nosave", value: "SavePoint" },
    { map: "gld2_gef", flag: "nosave", value: "SavePoint" },
    { map: "gld2_pay", flag: "nosave", value: "SavePoint" },
    { map: "gld2_prt", flag: "nosave", value: "SavePoint" },
    { map: "teg_dun01", flag: "nosave", value: "SavePoint" },
    { map: "teg_dun02", flag: "nosave", value: "SavePoint" },
    { map: "te_prtcas01", flag: "nosave", value: "SavePoint" },
    { map: "te_prtcas02", flag: "nosave", value: "SavePoint" },
    { map: "te_prtcas03", flag: "nosave", value: "SavePoint" },
    { map: "te_prtcas04", flag: "nosave", value: "SavePoint" },
    { map: "te_prtcas05", flag: "nosave", value: "SavePoint" },
    { map: "te_aldecas1", flag: "nosave", value: "SavePoint" },
    { map: "te_aldecas2", flag: "nosave", value: "SavePoint" },
    { map: "te_aldecas3", flag: "nosave", value: "SavePoint" },
    { map: "te_aldecas4", flag: "nosave", value: "SavePoint" },
    { map: "te_aldecas5", flag: "nosave", value: "SavePoint" },
    { map: "que_lhz", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif01", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif02", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif03", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif04", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif05", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif06", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif07", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif08", flag: "nosave", value: "SavePoint" },
    { map: "ma_zif09", flag: "nosave", value: "SavePoint" },
    { map: "que_avan01", flag: "nosave", value: "SavePoint" },
    { map: "un_myst", flag: "nosave", value: "SavePoint" },
    { map: "que_swat", flag: "nosave", value: "SavePoint" },
    { map: "rockmi2", flag: "nosave", value: "SavePoint" },
);
