// Auto-generated from rAthena specialpopup.txt.
// Re-generate with: python3 scripts/tools/import_rathena.py

registerMapFlag(
    { map: "herosria", flag: "specialpopup", value: "1" },
    { map: "hero_in1", flag: "specialpopup", value: "1" },
    { map: "hero_in2", flag: "specialpopup", value: "1" },
    { map: "hero_in3", flag: "specialpopup", value: "1" },
    { map: "hero_in4", flag: "specialpopup", value: "1" },
    { map: "hero_out1", flag: "specialpopup", value: "1" },
    { map: "hero_out2", flag: "specialpopup", value: "1" },
    { map: "hero_out3", flag: "specialpopup", value: "1" },
    { map: "hero_out4", flag: "specialpopup", value: "1" },
    { map: "hero_ent1", flag: "specialpopup", value: "1" },
    { map: "hero_ent2", flag: "specialpopup", value: "1" },
    { map: "hero_ent3", flag: "specialpopup", value: "1" },
    { map: "hero_tra", flag: "specialpopup", value: "2" },
    { map: "hero_dun1", flag: "specialpopup", value: "2" },
    { map: "bl_ice", flag: "specialpopup", value: "3" },
    { map: "bl_lava", flag: "specialpopup", value: "3" },
    { map: "bl_grass", flag: "specialpopup", value: "3" },
    { map: "bl_death", flag: "specialpopup", value: "3" },
    { map: "bl_soul", flag: "specialpopup", value: "3" },
    { map: "bl_venom", flag: "specialpopup", value: "3" },
    { map: "bl_temple", flag: "specialpopup", value: "3" },
    { map: "thana_step", flag: "specialpopup", value: "4" },
    { map: "tha_t07", flag: "specialpopup", value: "4" },
    { map: "tha_t08", flag: "specialpopup", value: "4" },
    { map: "tha_t09", flag: "specialpopup", value: "4" },
    { map: "tha_t10", flag: "specialpopup", value: "4" },
    { map: "tha_t11", flag: "specialpopup", value: "4" },
    { map: "tha_t12", flag: "specialpopup", value: "4" },
    { map: "ama_dun01", flag: "specialpopup", value: "5" },
    { map: "lhz_dun_n", flag: "specialpopup", value: "6" },
    { map: "bl_depth1", flag: "specialpopup", value: "7" },
    { map: "for_dun01", flag: "specialpopup", value: "8" },
    { map: "for_dun02", flag: "specialpopup", value: "8" },
    { map: "bl_depth2", flag: "specialpopup", value: "9" },
);
