// Auto-generated by scripts/tools/import_rathena.py. Do not edit by
// hand — re-run the importer to refresh. Imports every sibling .ts
// file in this directory plus every sub-directory's index.

import "./alberta";
import "./dewata";
import "./dicastes";
import "./eclage";
import "./einbech";
import "./einbroch";
import "./izlude";
import "./lasagna";
import "./lighthalzen";
import "./malangdo";
import "./malaya";
import "./prontera";
import "./rachel";
import "./rockridge";
import "./yggdrasil";
