-- Auto-generated by Tools.RathenaImporter (level_penalty).
-- Source: db/re/level_penalty.yml
-- Rows: 2
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `level_penalty` (`penalty_type`,`payload_json`) VALUES ('Exp','{"Type":"Exp","LevelDifferences":[{"Difference":16,"Rate":40},{"Difference":15,"Rate":115},{"Difference":14,"Rate":120},{"Difference":13,"Rate":125},{"Difference":12,"Rate":130},{"Difference":11,"Rate":135},{"Difference":10,"Rate":140},{"Difference":9,"Rate":135},{"Difference":8,"Rate":130},{"Difference":7,"Rate":125},{"Difference":6,"Rate":120},{"Difference":5,"Rate":115},{"Difference":4,"Rate":110},{"Difference":3,"Rate":105},{"Difference":-6,"Rate":95},{"Difference":-11,"Rate":90},{"Difference":-16,"Rate":85},{"Difference":-21,"Rate":60},{"Difference":-26,"Rate":35},{"Difference":-31,"Rate":10}]}');
REPLACE INTO `level_penalty` (`penalty_type`,`payload_json`) VALUES ('Drop','{"Type":"Drop","LevelDifferences":[{"Difference":16,"Rate":50},{"Difference":13,"Rate":60},{"Difference":10,"Rate":70},{"Difference":7,"Rate":80},{"Difference":4,"Rate":90},{"Difference":-4,"Rate":90},{"Difference":-7,"Rate":80},{"Difference":-10,"Rate":70},{"Difference":-13,"Rate":60},{"Difference":-16,"Rate":50}]}');
