-- Auto-generated by Tools.RathenaImporter (battleground_db).
-- Source: db/battleground_db.yml
-- Rows: 5
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `battleground_type_db` (`id`,`name`,`min_players`,`min_level`) VALUES (1,'Tierra Gorge',6,80);
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (1,'Novice');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (1,'SuperNovice');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (1,'Novice_High');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (1,'Baby');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (1,'Super_Baby');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (1,'Super_Novice_E');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (1,'Super_Baby_E');
REPLACE INTO `battleground_location_db` (`bg_id`,`map_name`,`start_event`,`team_a_respawn_x`,`team_a_respawn_y`,`team_a_quit_event`,`team_a_active_event`,`team_a_variable`,`team_b_respawn_x`,`team_b_respawn_y`,`team_b_quit_event`,`team_b_active_event`,`team_b_variable`) VALUES (1,'bat_a01','start#bat_a01::OnReadyCheck',50,374,'start#bat_a01::OnGuillaumeQuit','start#bat_a01::OnGuillaumeActive','$@TierraBG1_id1',42,16,'start#bat_a01::OnCroixQuit','start#bat_a01::OnCroixActive','$@TierraBG1_id2');
REPLACE INTO `battleground_location_db` (`bg_id`,`map_name`,`start_event`,`team_a_respawn_x`,`team_a_respawn_y`,`team_a_quit_event`,`team_a_active_event`,`team_a_variable`,`team_b_respawn_x`,`team_b_respawn_y`,`team_b_quit_event`,`team_b_active_event`,`team_b_variable`) VALUES (1,'bat_a02','start#bat_a02::OnReadyCheck',50,374,'start#bat_a02::OnGuillaumeQuit','start#bat_a02::OnGuillaumeActive','$@TierraBG2_id1',42,16,'start#bat_a02::OnCroixQuit','start#bat_a02::OnCroixActive','$@TierraBG2_id2');
REPLACE INTO `battleground_type_db` (`id`,`name`,`min_players`,`min_level`) VALUES (2,'Flavius',6,80);
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (2,'Novice');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (2,'SuperNovice');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (2,'Novice_High');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (2,'Baby');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (2,'Super_Baby');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (2,'Super_Novice_E');
REPLACE INTO `battleground_job_restriction_db` (`bg_id`,`job_aegis`) VALUES (2,'Super_Baby_E');
REPLACE INTO `battleground_location_db` (`bg_id`,`map_name`,`start_event`,`team_a_respawn_x`,`team_a_respawn_y`,`team_a_quit_event`,`team_a_active_event`,`team_a_variable`,`team_b_respawn_x`,`team_b_respawn_y`,`team_b_quit_event`,`team_b_active_event`,`team_b_variable`) VALUES (2,'bat_b01','start#bat_b01::OnReadyCheck',10,290,'start#bat_b01::OnGuillaumeQuit','start#bat_b01::OnGuillaumeActive','$@FlaviusBG1_id1',390,10,'start#bat_b01::OnCroixQuit','start#bat_b01::OnCroixActive','$@FlaviusBG1_id2');
REPLACE INTO `battleground_location_db` (`bg_id`,`map_name`,`start_event`,`team_a_respawn_x`,`team_a_respawn_y`,`team_a_quit_event`,`team_a_active_event`,`team_a_variable`,`team_b_respawn_x`,`team_b_respawn_y`,`team_b_quit_event`,`team_b_active_event`,`team_b_variable`) VALUES (2,'bat_b02','start#bat_b02::OnReadyCheck',10,290,'start#bat_b02::OnGuillaumeQuit','start#bat_b02::OnGuillaumeActive','$@FlaviusBG2_id1',390,10,'start#bat_b02::OnCroixQuit','start#bat_b02::OnCroixActive','$@FlaviusBG2_id2');
REPLACE INTO `battleground_type_db` (`id`,`name`,`min_players`,`min_level`) VALUES (3,'KVM (Level 80 and up)',5,80);
REPLACE INTO `battleground_location_db` (`bg_id`,`map_name`,`start_event`,`team_a_respawn_x`,`team_a_respawn_y`,`team_a_quit_event`,`team_a_active_event`,`team_a_variable`,`team_b_respawn_x`,`team_b_respawn_y`,`team_b_quit_event`,`team_b_active_event`,`team_b_variable`) VALUES (3,'bat_c01','KvM01_BG::OnStart',52,129,'KvM01_BG::OnGuillaumeQuit','KvM01_BG::OnGuillaumeActive','$@KvM01BG_id1',147,55,'KvM01_BG::OnCroixQuit','KvM01_BG::OnCroixActive','$@KvM01BG_id2');
REPLACE INTO `battleground_type_db` (`id`,`name`,`min_players`,`min_level`) VALUES (4,'KVM (Level 60~79)',5,60);
REPLACE INTO `battleground_location_db` (`bg_id`,`map_name`,`start_event`,`team_a_respawn_x`,`team_a_respawn_y`,`team_a_quit_event`,`team_a_active_event`,`team_a_variable`,`team_b_respawn_x`,`team_b_respawn_y`,`team_b_quit_event`,`team_b_active_event`,`team_b_variable`) VALUES (4,'bat_c02','KvM02_BG::OnStart',52,129,'KvM02_BG::OnGuillaumeQuit','KvM02_BG::OnGuillaumeActive','$@KvM02BG_id1',147,55,'KvM02_BG::OnCroixQuit','KvM02_BG::OnCroixActive','$@KvM02BG_id2');
REPLACE INTO `battleground_type_db` (`id`,`name`,`min_players`,`min_level`) VALUES (5,'KVM (Level 59 and below',5,1);
REPLACE INTO `battleground_location_db` (`bg_id`,`map_name`,`start_event`,`team_a_respawn_x`,`team_a_respawn_y`,`team_a_quit_event`,`team_a_active_event`,`team_a_variable`,`team_b_respawn_x`,`team_b_respawn_y`,`team_b_quit_event`,`team_b_active_event`,`team_b_variable`) VALUES (5,'bat_c03','KvM03_BG::OnStart',52,129,'KvM03_BG::OnGuillaumeQuit','KvM03_BG::OnGuillaumeActive','$@KvM03BG_id1',147,55,'KvM03_BG::OnCroixQuit','KvM03_BG::OnCroixActive','$@KvM03BG_id2');
