-- Auto-generated by Tools.RathenaImporter (pet_db).
-- Source: db/re/pet_db.yml
-- Rows: 102
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('PORING','Unripe_Apple','Poring_Egg','Backpack','Apple_Juice',3,NULL,NULL,50,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritical,1;
   bonus bLuk,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritical,1;
   bonus bLuk,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DROPS','Orange_Juice','Drops_Egg','Backpack','Yellow_Herb',4,NULL,NULL,40,NULL,NULL,NULL,1500,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bBaseAtk,5;
   bonus bHit,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bBaseAtk,3;
   bonus bHit,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('POPORING','Bitter_Herb','Poporing_Egg','Backpack','Green_Herb',5,NULL,NULL,30,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubEle,Ele_Poison,15;
   bonus bLuk,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubEle,Ele_Poison,10;
   bonus bLuk,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('LUNATIC','Rainbow_Carrot','Lunatic_Egg','Silk_Ribbon','Carrot_Juice',4,NULL,NULL,40,NULL,NULL,NULL,1500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritical,3;
   bonus bBaseAtk,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritical,2;
   bonus bBaseAtk,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('PICKY','Earthworm_The_Dude','Picky_Egg','Tiny_Egg_Shell','Red_Herb',4,NULL,NULL,40,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bBaseAtk,8;
   bonus bStr,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bBaseAtk,5;
   bonus bStr,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('CHONCHON','Rotten_Fish','Chonchon_Egg','Monster_Oxygen_Mask','Pet_Food',6,NULL,NULL,30,NULL,NULL,NULL,1500,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bAgi,2;
   bonus bFlee,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bAgi,1;
   bonus bFlee,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('STEEL_CHONCHON','Lusty_Iron','Steel_Chonchon_Egg','Monster_Oxygen_Mask','Iron_Ore',5,NULL,NULL,20,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bFlee,9;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bFlee,6;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('HUNTER_FLY','Monster_Juice','Hunter_Fly_Egg','Monster_Oxygen_Mask','Red_Gemstone',5,NULL,NULL,10,NULL,NULL,NULL,500,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bFlee2,2;
   bonus bHit,1;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bFlee2,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SAVAGE_BABE','Sweet_Milk','Savage_Bebe_Egg','Green_Lace','Pet_Food',7,NULL,NULL,40,NULL,NULL,NULL,1500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bVit,2;
   bonus bMaxHP,75;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bVit,1;
   bonus bMaxHP,50;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DESERT_WOLF_B','Well_Dried_Bone','Baby_Desert_Wolf_Egg','Transparent_Headgear','Pet_Food',6,NULL,NULL,40,NULL,NULL,NULL,1000,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bInt,2;
   bonus bMaxSP,75;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bInt,1;
   bonus bMaxSP,50;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ROCKER','Singing_Flower','Rocker_Egg','Rocker_Glasses','Pet_Food',1,NULL,NULL,30,NULL,NULL,NULL,1500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bHPrecovRate,8;
   bonus bMaxHP,38;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bHPrecovRate,5;
   bonus bMaxHP,25;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SPORE','Dew_Laden_Moss','Spore_Egg','Bark_Shorts','Pet_Food',3,NULL,NULL,30,NULL,NULL,NULL,1500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bHit,8;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bHit,5;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('POISON_SPORE','Deadly_Noxious_Herb','Poison_Spore_Egg','Bark_Shorts','Pet_Food',3,NULL,NULL,20,NULL,NULL,NULL,1000,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bStr,2;
   bonus bInt,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bStr,1;
   bonus bInt,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('PECOPECO','Fatty_Chubby_Earthworm','PecoPeco_Egg','Battered_Pot','Pet_Food',4,NULL,NULL,30,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMaxHP,200;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMaxHP,150;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SMOKIE','Baked_Yam','Smokie_Egg','Red_Muffler','Pet_Food',4,NULL,NULL,30,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bFlee2,1;
   bonus bAgi,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bFlee2,1;
   bonus bAgi,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('YOYO','Tropical_Banana','Yoyo_Egg','Monkey_Circlet','Banana_Juice',5,NULL,NULL,20,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritical,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritical,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ORK_WARRIOR','Horror_Of_Tribe','Orc_Warrior_Egg','Wild_Flower','Pet_Food',5,NULL,NULL,20,NULL,NULL,NULL,500,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bBaseAtk,15;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bBaseAtk,10;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MUNAK','No_Recipient','Munak_Egg','Punisher','Pet_Food',3,NULL,NULL,20,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bDef,2;
   bonus bInt,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bDef,1;
   bonus bInt,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DOKEBI','Old_Broom','Dokkaebi_Egg','Wig','Pet_Food',4,NULL,NULL,20,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMatkRate,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMatkRate,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SOHEE','Silver_Knife_Of_Chaste','Sohee_Egg','Golden_Bell','Pet_Food',3,NULL,NULL,10,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bStr,2;
   bonus bDex,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bStr,1;
   bonus bDex,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ISIS','Armlet_Of_Obedience','Isis_Egg','Queen''s_Hair_Ornament','Pet_Food',3,NULL,NULL,10,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddClass,Class_All,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddClass,Class_All,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('PETIT','Shining_Stone','Green_Petite_Egg','Stellar_Hairpin','Pet_Food',4,NULL,NULL,20,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bAspdRate,1;
   bonus bAgi,1;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bAspdRate,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DEVIRUCHI','Contracts_In_Shadow','Deviruchi_Egg','Pacifier','Shoot',2,NULL,NULL,10,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddClass,Class_All,1;
   bonus bMatkRate,1;
   bonus bMaxHPrate,1;
   bonus bMaxSPrate,1;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddClass,Class_All,1;
   bonus bMatkRate,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('BAPHOMET_','Book_Of_Devil','Bapho_Jr._Egg','Skull_Helm','Honey',2,NULL,NULL,10,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bResEff,Eff_Stun,200;
   bonus bMdef,2;
   bonus bDef,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bResEff,Eff_Stun,100;
   bonus bMdef,1;
   bonus bDef,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('BON_GUN','Heart_Of_Her','Bongun_Egg','Sword_Of_Grave_Keeper','Pet_Food',4,NULL,NULL,30,NULL,NULL,NULL,500,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bResEff,Eff_Stun,200;
   bonus bVit,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bResEff,Eff_Stun,100;
   bonus bVit,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ZHERLTHSH','Prohibition_Red_Candle','Zherlthsh_Egg',NULL,'Immortal_Heart',7,NULL,NULL,10,NULL,NULL,NULL,300,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddRace,RC_DemiHuman,3;
   bonus2 bMagicAddRace,RC_DemiHuman,3;
   bonus2 bAddRace,RC_Player_Human,3;
   bonus2 bMagicAddRace,RC_Player_Human,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddRace,RC_DemiHuman,2;
   bonus2 bMagicAddRace,RC_DemiHuman,2;
   bonus2 bAddRace,RC_Player_Human,2;
   bonus2 bMagicAddRace,RC_Player_Human,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ALICE','Sway_Apron','Alice_Egg',NULL,'White_Potion',2,NULL,NULL,20,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubRace,RC_DemiHuman,2;
   bonus2 bSubRace,RC_Player_Human,2;
   bonus bMdef,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubRace,RC_DemiHuman,1;
   bonus2 bSubRace,RC_Player_Human,1;
   bonus bMdef,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('EVENT_RICECAKE',NULL,'Rice_Cake_Egg',NULL,'Green_Herb',3,NULL,NULL,50,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubEle,Ele_Neutral,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubEle,Ele_Neutral,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GOBLINE_XMAS','Sweet_Candy_Striper','Santa_Goblin_Egg',NULL,'Scell',3,NULL,NULL,50,NULL,NULL,NULL,2000,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubEle,Ele_Water,2;
   bonus bMaxHP,45;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubEle,Ele_Water,1;
   bonus bMaxHP,30;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('CHUNG_E','Tantanmen','Chung_E_Egg',NULL,'Bun_',3,NULL,NULL,50,NULL,NULL,NULL,2000,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubRace,RC_DemiHuman,2;
   bonus2 bSubRace,RC_Player_Human,2;
   bonus bDef,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubRace,RC_DemiHuman,1;
   bonus2 bSubRace,RC_Player_Human,1;
   bonus bDef,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('CHUNG_E_','Tantanmen','Chung_E_Egg',NULL,'Bun_',3,NULL,NULL,50,NULL,NULL,NULL,2000,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubRace,RC_DemiHuman,2;
   bonus2 bSubRace,RC_Player_Human,2;
   bonus bDef,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubRace,RC_DemiHuman,1;
   bonus2 bSubRace,RC_Player_Human,1;
   bonus bDef,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ECLIPSE_P',NULL,'Spring_Rabbit_Egg',NULL,'Bok_Choy',3,NULL,NULL,50,NULL,NULL,NULL,2000,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GOBLIN_1','Knife_Goblin_Ring','Knife_Goblin_Egg',NULL,'Green_Apple',3,NULL,NULL,50,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GOBLIN_2','Flail_Goblin_Ring','Flail_Goblin_Egg',NULL,'Green_Apple',3,NULL,NULL,50,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GOBLIN_4','Hammer_Goblin_Ring','Hammer_Goblin_Egg',NULL,'Green_Apple',3,NULL,NULL,50,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DELETER_','Holy_Marble','Red_Deleter_Egg',NULL,'Whole_Barbecue',4,NULL,NULL,20,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DIABOLIC','Red_Burning_Stone','Diabolic_Egg',NULL,'Meat_Veg_Skewer',2,NULL,NULL,10,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('WANDER_MAN','Skull_Of_Vagabond','Wanderer_Egg',NULL,'Spirit_Liquor',2,NULL,NULL,20,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bAgi,4;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bAgi,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('P_CHUNG_E',NULL,'New_Year_Doll_Egg',NULL,'Mojji',3,NULL,NULL,30,NULL,NULL,NULL,800,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GOLEM','Magical_Lithography','Golem_Egg','Windup_Spring','Mystic_Stone',7,NULL,NULL,20,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMaxHP,150;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMaxHP,100;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MARIONETTE','Delicious_Shaved_Ice','Marionette_Egg','Star_Hairband','Small_Snow_Flower',3,NULL,NULL,10,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  petautobonus "{ bonus2 bSubEle,Ele_Neutral,2; heal 100,0; }",100,5000,BF_SHORT|BF_NORMAL;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  petautobonus "{ bonus2 bSubEle,Ele_Neutral,2; heal 100,0; }",100,3000,BF_SHORT|BF_NORMAL;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MEDUSA','Splendid_Mirror','Medusa_Egg','Queen''s_Coronet','Apple_Pudding',3,NULL,NULL,10,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bResEff,Eff_Stone,800;
   bonus bVit,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bResEff,Eff_Stone,500;
   bonus bVit,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('WHISPER','Fit_Pipe','Whisper_Egg','Spirit_Chain_','Damp_Darkness',7,NULL,NULL,20,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'if (getpetinfo(PETINFO_INTIMATE) >= PET_INTIMATE_LOYAL) {
   skill "TF_HIDING",1;
   bonus bFlee,10;
} else {
   skill "TF_HIDING",1;
   bonus bFlee,7;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GOBLIN_LEADER','Staff_Of_Leader','Goblin_Leader_Egg','Nice_Badge','Big_Cell',7,NULL,NULL,10,NULL,NULL,NULL,50,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddRace,RC_DemiHuman,5;
   bonus2 bAddRace,RC_Player_Human,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddRace,RC_DemiHuman,3;
   bonus2 bAddRace,RC_Player_Human,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SUCCUBUS','Boy''s_Naivety','Succubus_Egg','Black_Butterfly_Mask','Vital_Flower_',3,NULL,NULL,10,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bHPDrainRate,30,5;
   bonus bMaxHPrate,1;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bHPDrainRate,30,5;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('INCUBUS','Gril''s_Naivety','Incubus_Egg','Ball_Mask','Vital_Flower',3,NULL,NULL,10,NULL,NULL,NULL,50,0,NULL,NULL,NULL,NULL,'if (getpetinfo(PETINFO_INTIMATE) >= PET_INTIMATE_LOYAL) {
   bonus2 bSPDrainRate,30,1;
   bonus bMaxSPrate,5;
} else {
   bonus2 bSPDrainRate,30,1;
   bonus bMaxSPrate,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('NIGHTMARE_TERROR','Hell_Contract','Nightmare_Terror_Egg','Hell_Horn','Fresh_Plant',3,NULL,NULL,10,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bInt,1;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bResEff,Eff_Sleep,10000;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SHINOBI','Kuloren','Shinobi_Egg','Wine_On_Sleeve','Grilled_Rice_Cake',7,NULL,NULL,20,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bAgi,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bAgi,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MIYABI_NINGYO','Gril_Doll','Miyabi_Ningyo_Egg','Summer_Fan','Well_Ripened_Berry',3,NULL,NULL,15,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bVariableCastrate,-5;
   bonus bInt,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bVariableCastrate,-3;
   bonus bInt,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('WICKED_NYMPH','Charming_Lotus','Wicked_Nymph_Egg','Jade_Trinket','Morning_Dew',3,NULL,NULL,15,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bSPrecovRate,8;
   bonus bMaxSP,45;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bSPrecovRate,5;
   bonus bMaxSP,30;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('STONE_SHOOTER','Oilpalm_Coconut','Stone_Shooter_Egg','Apro_Hair','Plant_Neutrient',7,NULL,NULL,20,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubEle,Ele_Fire,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubEle,Ele_Fire,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DULLAHAN','Luxury_Whisky_Bottle','Dullahan_Egg','Death_Coil','Sunset_On_The_Rock',3,NULL,NULL,10,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritAtkRate,8;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritAtkRate,5;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('LOLI_RURI','Very_Red_Juice','Loli_Ruri_Egg','Fashionable_Glasses','Pumpkin_Pie_',3,NULL,NULL,15,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus3 bAutoSpellWhenHit,"AL_HEAL",2,10;
   bonus bMaxHPrate,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus3 bAutoSpellWhenHit,"AL_HEAL",1,10;
   bonus bMaxHPrate,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('CIVIL_SERVANT','Fan_Of_Wind','Civil_Servant_Egg','Golden_Earing','Flavored_Alcohol',3,NULL,NULL,10,NULL,NULL,NULL,500,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMaxSP,15;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMaxSP,10;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('LEAF_CAT','Very_Soft_Plant','Leaf_Cat_Egg','Green_Lucky_Bag','Fish_With_Blue_Back',7,NULL,NULL,20,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bSubRace,RC_Brute,5;
   bonus2 bSubRace,RC_Player_Doram,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bSubRace,RC_Brute,3;
   bonus2 bSubRace,RC_Player_Doram,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('BACSOJIN_','Shiny_Wing_Gown','Bacsojin_Egg','Round_Hair_Ornament','Traditional_Cookie',7,NULL,NULL,10,NULL,NULL,NULL,2000,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('IMP','Flaming_Ice','Imp_Egg','Horn_Protector','Flame_Gemstone',3,NULL,NULL,10,NULL,NULL,NULL,200,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddEle,Ele_Fire,2;
   bonus2 bSubEle,Ele_Fire,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddEle,Ele_Fire,1;
   bonus2 bSubEle,Ele_Fire,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('E_CRAMP','Leaf_Cat_Ball','Mystic_Leaf_Cat_Ball',NULL,NULL,0,NULL,0,0,0,NULL,0,50,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('E_HYDRA','Leaf_Cat_Ball','Mystic_Leaf_Cat_Ball',NULL,NULL,0,NULL,0,0,0,NULL,0,50,0,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('J_TAINI',NULL,'Egg_Of_Tiny',NULL,'Apple',3,NULL,NULL,10,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('XMAS_LUNATIC',NULL,'Snow_Rabbit_Egg',NULL,'Candy',3,NULL,NULL,10,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_CORDIAL) {
  /* bonus2 bExpAddRace,RC_All,5; */
  bonus bMatkRate,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('TIKBALANG','Tikbalang_Belt','Tikbalang_Pet',NULL,'Monster''s_Feed',8,NULL,NULL,10,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus2 bAddDamageClass,2317,10;
  bonus2 bAddDamageClass,2318,10;
  bonus2 bAddDamageClass,2319,10;
  bonus2 bAddDamageClass,2320,10;
  bonus2 bAddDamageClass,2321,10;
  bonus2 bAddDamageClass,2322,10;
  bonus2 bAddDamageClass,2327,10;
  bonus2 bAddDamageClass,2332,10;
  bonus2 bAddDamageClass,2333,10;
  bonus bMdef,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus2 bAddDamageClass,2317,10;
  bonus2 bAddDamageClass,2318,10;
  bonus2 bAddDamageClass,2319,10;
  bonus2 bAddDamageClass,2320,10;
  bonus2 bAddDamageClass,2321,10;
  bonus2 bAddDamageClass,2322,10;
  bonus2 bAddDamageClass,2327,10;
  bonus2 bAddDamageClass,2332,10;
  bonus2 bAddDamageClass,2333,10;
  bonus bMdef,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MARIN','Juicy_Fruit','Marin_Egg','Tw_Backpack','Fruit_Sundae',3,NULL,NULL,50,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('LITTLE_PORING','Unripe_Apple2','Novice_Poring_Egg',NULL,'Apple_Juice',3,NULL,NULL,1000,0,NULL,0,5000,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bHPrecovRate,75;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bHPrecovRate,50;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('NINE_TAIL','Sap_Jelly','Nine_Tail_Egg',NULL,'Suspicious_Bottle',4,NULL,NULL,50,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritical,3;
   bonus bHit,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritical,2;
   bonus bHit,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GREMLIN','Airship_Part','Gremlin_Egg',NULL,'Cheap_Lubricant',4,NULL,NULL,50,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bHit,1;
   bonus bDex,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bHit,1;
   bonus bDex,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MUMMY','Elixir_Bandage','Mummy_Egg',NULL,'Mementos',7,NULL,NULL,50,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bHit,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bHit,4;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('TEDDY_BEAR','Little_Dall_Needle','Teddy_Bear_Egg',NULL,'Wad_Of_Cotton',3,NULL,NULL,50,NULL,NULL,NULL,2000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMaxSP,100;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMaxSP,50;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MASTERING',NULL,'Mastering_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritical,3;
   bonus bLuk,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritical,2;
   bonus bLuk,3;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bCritical,1;
   bonus bLuk,3;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bCritical,1;
   bonus bLuk,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('METALLER',NULL,'Metaller_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddRace,RC_Plant,6;
   bonus2 bMagicAddRace,RC_Plant,6;
   bonus bHPrecovRate,20;
   bonus bMaxHP,70;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddRace,RC_Plant,3;
   bonus2 bMagicAddRace,RC_Plant,3;
   bonus bHPrecovRate,15;
   bonus bMaxHP,55;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bHPrecovRate,10;
   bonus bMaxHP,38;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bHPrecovRate,5;
   bonus bMaxHP,25;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ANGELING',NULL,'Angeling_Egg',NULL,'Pet_Food',1,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMaxHPrate,2;
   bonus bHealPower,8;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMaxHPrate,2;
   bonus bHealPower,6;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bMaxHPrate,1;
   bonus bHealPower,4;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bMaxHPrate,1;
   bonus bHealPower,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('MOONLIGHT',NULL,'Moonlight_Egg',NULL,'High_Class_Pet_food',1,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus bCritical,6;
  bonus bHit,6;
  petautobonus "{ bonus2 bHPRegenRate,500,1000; bonus2 bSPRegenRate,20,1000; }",30,5000,BF_WEAPON|BF_SHORT;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus bCritical,5;
  bonus bHit,5;
  petautobonus "{ bonus2 bHPRegenRate,400,1000; bonus2 bSPRegenRate,10,1000; }",30,5000,BF_WEAPON|BF_SHORT;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
  bonus bCritical,4;
  bonus bHit,4;
  petautobonus "{ bonus2 bHPRegenRate,300,1000; }",20,5000,BF_WEAPON|BF_SHORT;
} else {
  bonus bCritical,3;
  bonus bHit,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SAVAGE',NULL,'Savage_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bVit,2;
   bonus bMaxHP,200;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bVit,2;
   bonus bMaxHP,100;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bVit,2;
   bonus bMaxHP,50;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bVit,1;
   bonus bMaxHP,50;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('HIGH_ORC',NULL,'High_Orc_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bBaseAtk,25;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bBaseAtk,20;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bBaseAtk,15;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bBaseAtk,10;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('CHOCO',NULL,'Choco_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bLongAtkRate,3;
   bonus bCritical,9;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bLongAtkRate,2;
   bonus bCritical,7;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bLongAtkRate,1;
   bonus bCritical,5;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bCritical,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ANCIENT_MUMMY',NULL,'Ancient_Mummy_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddRace,RC_Dragon,6;
   bonus2 bMagicAddRace,RC_Dragon,6;
   bonus bHit,6;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddRace,RC_Dragon,3;
   bonus2 bMagicAddRace,RC_Dragon,3;
   bonus bHit,6;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bHit,5;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bHit,4;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('AM_MUT',NULL,'Ammut_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMatkRate,4;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMatkRate,3;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bMatkRate,2;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bMatkRate,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('CAT_O_NINE_TAIL',NULL,'Cat_O_Nine_Tail_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus bCritical,5;
  bonus bHit,5;
  petautobonus "{ bonus2 bHPRegenRate,400,1000; }",20,5000,BF_WEAPON|BF_SHORT;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus bCritical,4;
  bonus bHit,4;
  petautobonus "{ bonus2 bHPRegenRate,300,1000; }",20,5000,BF_WEAPON|BF_SHORT;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
  bonus bCritical,3;
  bonus bHit,3;
} else {
  bonus bCritical,2;
  bonus bHit,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('GRAND_PECO',NULL,'Grand_Peco_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMaxHP,400;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMaxHP,300;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bMaxHP,200;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bMaxHP,150;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('HYEGUN',NULL,'Hyegun_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus bVit,4;
  bonus2 bResEff,Eff_Stun,400;
  bonus2 bSPDrainRate,10,1;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus bVit,3;
  bonus2 bResEff,Eff_Stun,300;
  bonus2 bSPDrainRate,10,1;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
  bonus bVit,2;
  bonus2 bResEff,Eff_Stun,200;
} else {
  bonus bVit,1;
  bonus2 bResEff,Eff_Stun,100;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('HODREMLIN',NULL,'Hodremlin_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritAtkRate,9;
   bonus bHit,2;
   bonus bDex,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritAtkRate,7;
   bonus bHit,2;
   bonus bDex,2;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bHit,1;
   bonus bDex,2;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bHit,1;
   bonus bDex,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('XM_TEDDY_BEAR',NULL,'Xm_Teddybear_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus bMaxSP,150;
  petautobonus "{ bonus2 bSPRegenRate,40,1000; }",30,5000,BF_MAGIC;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus bMaxSP,150;
  petautobonus "{ bonus2 bSPRegenRate,30,1000; }",30,5000,BF_MAGIC;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
  bonus bMaxSP,100;
} else {
  bonus bMaxSP,50;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DR_EGGRING',NULL,'Eggring_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bBaseAtk,9;
   bonus bHit,9;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bBaseAtk,7;
   bonus bHit,7;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bBaseAtk,5;
   bonus bHit,5;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bBaseAtk,3;
   bonus bHit,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DR_LUNATIC',NULL,'Leaf_Lunatic_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddRace,RC_Formless,6;
   bonus2 bMagicAddRace,RC_Formless,6;
   bonus bCritical,5;
   bonus bBaseAtk,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddRace,RC_Formless,3;
   bonus2 bMagicAddRace,RC_Formless,3;
   bonus bCritical,4;
   bonus bBaseAtk,4;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bCritical,3;
   bonus bBaseAtk,3;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bCritical,2;
   bonus bBaseAtk,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('LITTLE_ISIS',NULL,'Littleisis_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bAddClass,Class_All,4;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bAddClass,Class_All,3;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus2 bAddClass,Class_All,2;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus2 bAddClass,Class_All,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DIABOLIC2','Red_Burning_Stone','Diabolic_Egg2',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus bAtkRate,2;
  bonus bMatkRate,2;
  bonus bMaxHPrate,2;
  bonus bMaxSPrate,2;
  bonus5 bAutoSpell,"MG_FIREBOLT",3,50,BF_WEAPON|BF_SHORT,1;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus bAtkRate,2;
  bonus bMatkRate,2;
  bonus bMaxHPrate,1;
  bonus bMaxSPrate,1;
  bonus5 bAutoSpell,"MG_FIREBOLT",3,50,BF_WEAPON|BF_SHORT,1;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
  bonus bAtkRate,1;
  bonus bMatkRate,1;
  bonus bMaxHPrate,1;
  bonus bMaxSPrate,1;
} else {
  bonus bAtkRate,1;
  bonus bMatkRate,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DELETER_2',NULL,'Red_Deleter_Egg2',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bAspdRate,3;
   bonus bAgi,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bAspdRate,2;
   bonus bAgi,2;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bAspdRate,1;
   bonus bAgi,1;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bAspdRate,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('SWEETS_DROPS',NULL,'Sweets_Drops_Egg',NULL,'Candy',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus2 bExpAddClass,Class_All,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('NIGHTMARE_TERROR_H',NULL,'Nightmare_TerrorH_EGG',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bResEff,Eff_Sleep,10000;
   bonus bMaxSPrate,3;
   bonus bInt,4;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bResEff,Eff_Sleep,10000;
   bonus bMaxSPrate,1;
   bonus bInt,3;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bInt,2;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bInt,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('WANDER_MAN_H',NULL,'Wanderer_H_EGG',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bCritAtkRate,7;
   bonus bCritical,3;
   bonus bAgi,4;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bCritAtkRate,5;
   bonus bCritical,2;
   bonus bAgi,4;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bCritical,1;
   bonus bAgi,4;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bAgi,4;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ALIOT',NULL,'Aliot_EGG',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bAspdRate,5;
   bonus bHit,12;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bAspdRate,4;
   bonus bHit,9;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bAspdRate,3;
   bonus bHit,6;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bAspdRate,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ALICEL',NULL,'Alicel_EGG',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bMagicAtkEle,Ele_Neutral,5;
   bonus bVariableCastrate,-5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bMagicAtkEle,Ele_Neutral,3;
   bonus bVariableCastrate,-4;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bVariableCastrate,-3;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bVariableCastrate,-2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ALIZA',NULL,'Aliza_EGG',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bMdef,7;
   bonus bHealPower,6;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bMdef,6;
   bonus bHealPower,4;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bMdef,5;
   bonus bHealPower,2;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bMdef,4;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('EP17_2_CHILD_ADMIN1',NULL,'Ep17_2_C_Admin1_Egg','Ep_17_2_C_Admin1_Acc','Cloud_Cotton',2,NULL,NULL,20,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus2 bAddRace2,RC2_EP172BETA,10;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus2 bAddRace2,RC2_EP172BETA,6;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
  bonus2 bAddRace2,RC2_EP172BETA,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('EP17_2_CHILD_ADMIN2',NULL,'Ep17_2_C_Admin2_Egg','Ep_17_2_C_Admin2_Acc','Pet_Food',2,NULL,NULL,20,NULL,NULL,NULL,1000,NULL,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
  bonus2 bAddRace2,RC2_EP172ALPHA,15;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
  bonus2 bAddRace2,RC2_EP172ALPHA,8;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
  bonus2 bAddRace2,RC2_EP172ALPHA,4;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('WILOW',NULL,'Wilow_Egg',NULL,'Tree_Of_Archer_1',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus bInt,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus bInt,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('ROWEEN',NULL,'Roween_Egg',NULL,'Rotten_Meat',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bMagicAtkEle,Ele_Wind,3;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bMagicAtkEle,Ele_Wind,2;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DARK_PRIEST',NULL,'Dark_Priest_Egg',NULL,'Evil_Water',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bMagicAddEle,Ele_Holy,5;
   bonus bInt,2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bMagicAddEle,Ele_Holy,3;
   bonus bInt,1;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('DESERT_WOLF',NULL,'Desert_Wolf_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bMagicAtkEle,Ele_Earth,5;
   bonus bInt,4;
   bonus bMaxSP,130;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bMagicAtkEle,Ele_Earth,3;
   bonus bInt,3;
   bonus bMaxSP,105;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bInt,2;
   bonus bMaxSP,75;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bInt,1;
   bonus bMaxSP,50;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('FIRE_GOLEM',NULL,'Fire_Golem_Egg',NULL,'Pet_Food',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,1,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bMagicAtkEle,Ele_Fire,5;
   bonus bMaxHP,500;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bMagicAtkEle,Ele_Fire,3;
   bonus bMaxHP,400;
} else if (.@i >= PET_INTIMATE_NEUTRAL) {
   bonus bMaxHP,300;
} else if (.@i >= PET_INTIMATE_AWKWARD || .@i >= PET_INTIMATE_SHY) {
   bonus bMaxHP,200;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('FARMILIAR','Fruits_Set_Trap','Farmiliar_Egg',NULL,'Mixed_Fruits_Juice',2,NULL,NULL,15,NULL,NULL,NULL,2000,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bResEff,Eff_Curse,2000;
   bonus bInt,5;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bResEff,Eff_Curse,1000;
   bonus bInt,3;
}
',NULL);
REPLACE INTO `pet_db` (`mob_aegis`,`tame_item`,`egg_item`,`equip_item`,`food_item`,`fullness`,`hunger_delay`,`intimacy_start`,`intimacy_fed`,`intimacy_overfed`,`intimacy_hungry`,`intimacy_owner_die`,`capture_rate`,`special_performance`,`attack_rate`,`retaliate_rate`,`change_target_rate`,`allow_auto_feed`,`script`,`support_script`) VALUES ('HORNET',NULL,'aegis_9155',NULL,'Apple_Pudding',2,NULL,NULL,15,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,'.@i = getpetinfo(PETINFO_INTIMATE);
if (.@i >= PET_INTIMATE_LOYAL) {
   bonus2 bMagicAtkEle,Ele_Wind,2;
   bonus bVariableCastrate,-2;
} else if (.@i >= PET_INTIMATE_CORDIAL) {
   bonus2 bMagicAtkEle,Ele_Wind,1;
   bonus bVariableCastrate,-1;
}
',NULL);
