-- Auto-generated by Tools.RathenaImporter (magicmushroom_db).
-- Source: db/re/magicmushroom_db.yml
-- Rows: 23
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('SM_MAGNUM');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('SM_ENDURE');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('MG_SIGHT');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('AL_RUWACH');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('AL_CRUCIS');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('AL_ANGELUS');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('AC_CONCENTRATION');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('KN_AUTOCOUNTER');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('PR_MAGNIFICAT');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('BS_HAMMERFALL');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('BS_MAXIMIZE');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('NV_FIRSTAID');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('TF_BACKSLIDING');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('TF_PICKSTONE');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('MG_ENERGYCOAT');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('CR_AUTOGUARD');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('CR_PROVIDENCE');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('MO_CALLSPIRITS');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('MO_EXPLOSIONSPIRITS');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('DC_SCREAM');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('GS_GLITTERING');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('NJ_TATAMIGAESHI');
REPLACE INTO `magicmushroom_db` (`skill_name`) VALUES ('NJ_UTSUSEMI');
