-- Auto-generated by Tools.RathenaImporter (item_cash).
-- Source: db/item_cash.yml + project default catalog
-- Rows: 7
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `item_cash_db` (`tab`) VALUES ('New');
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('New','Bubble_Gum',800);
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('New','Battle_Manual',500);
REPLACE INTO `item_cash_db` (`tab`) VALUES ('Hot');
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Hot','Token_Of_Siegfried',1000);
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Hot','Glass_Of_Illusion',400);
REPLACE INTO `item_cash_db` (`tab`) VALUES ('Limited');
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Limited','Convex_Mirror',300);
REPLACE INTO `item_cash_db` (`tab`) VALUES ('Scrolls');
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Scrolls','Spark_Candy',250);
REPLACE INTO `item_cash_db` (`tab`) VALUES ('Consumables');
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Consumables','White_Potion',100);
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Consumables','Blue_Potion',120);
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Consumables','Yggdrasilberry',800);
REPLACE INTO `item_cash_db` (`tab`) VALUES ('Other');
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Other','Anodyne',200);
REPLACE INTO `item_cash_db` (`tab`) VALUES ('Sale');
REPLACE INTO `item_cash_entry_db` (`tab`,`item_aegis`,`price`) VALUES ('Sale','Bubble_Gum',400);
