-- Auto-generated by Tools.RathenaImporter (guild_skill_tree).
-- Source: db/re/guild_skill_tree.yml
-- Rows: 19
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_APPROVAL','{"Id":"GD_APPROVAL","MaxLevel":1}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_KAFRACONTRACT','{"Id":"GD_KAFRACONTRACT","MaxLevel":1,"Required":[{"Id":"GD_APPROVAL","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_GUARDRESEARCH','{"Id":"GD_GUARDRESEARCH","MaxLevel":1,"Required":[{"Id":"GD_APPROVAL","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_GUARDUP','{"Id":"GD_GUARDUP","MaxLevel":3}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_EXTENSION','{"Id":"GD_EXTENSION","MaxLevel":10}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_GLORYGUILD','{"Id":"GD_GLORYGUILD","MaxLevel":0}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_LEADERSHIP','{"Id":"GD_LEADERSHIP","MaxLevel":5}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_GLORYWOUNDS','{"Id":"GD_GLORYWOUNDS","MaxLevel":5}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_SOULCOLD','{"Id":"GD_SOULCOLD","MaxLevel":5,"Required":[{"Id":"GD_GLORYWOUNDS","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_HAWKEYES','{"Id":"GD_HAWKEYES","MaxLevel":5,"Required":[{"Id":"GD_LEADERSHIP","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_BATTLEORDER','{"Id":"GD_BATTLEORDER","MaxLevel":1,"Required":[{"Id":"GD_APPROVAL","Level":1},{"Id":"GD_EXTENSION","Level":2}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_REGENERATION','{"Id":"GD_REGENERATION","MaxLevel":3,"Required":[{"Id":"GD_APPROVAL","Level":1},{"Id":"GD_EXTENSION","Level":5},{"Id":"GD_BATTLEORDER","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_RESTORE','{"Id":"GD_RESTORE","MaxLevel":1,"Required":[{"Id":"GD_REGENERATION","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_EMERGENCYCALL','{"Id":"GD_EMERGENCYCALL","MaxLevel":1,"Required":[{"Id":"GD_APPROVAL","Level":1},{"Id":"GD_GUARDRESEARCH","Level":1},{"Id":"GD_EXTENSION","Level":5},{"Id":"GD_BATTLEORDER","Level":1},{"Id":"GD_REGENERATION","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_DEVELOPMENT','{"Id":"GD_DEVELOPMENT","MaxLevel":1}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_GUILD_STORAGE','{"Id":"GD_GUILD_STORAGE","MaxLevel":5,"Required":[{"Id":"GD_EMERGENCYCALL","Level":1},{"Id":"GD_EXTENSION","Level":10},{"Id":"GD_SOULCOLD","Level":1},{"Id":"GD_HAWKEYES","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_CHARGESHOUT_FLAG','{"Id":"GD_CHARGESHOUT_FLAG","MaxLevel":1,"Required":[{"Id":"GD_EMERGENCYCALL","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_CHARGESHOUT_BEATING','{"Id":"GD_CHARGESHOUT_BEATING","MaxLevel":1,"Required":[{"Id":"GD_CHARGESHOUT_FLAG","Level":1}]}');
REPLACE INTO `guild_skill_tree` (`skill_name`,`payload_json`) VALUES ('GD_EMERGENCY_MOVE','{"Id":"GD_EMERGENCY_MOVE","MaxLevel":1,"Required":[{"Id":"GD_LEADERSHIP","Level":1},{"Id":"GD_GLORYWOUNDS","Level":1}]}');
