-- Auto-generated by Tools.RathenaImporter (exp_guild).
-- Source: db/re/exp_guild.yml
-- Rows: 49
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (1,100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (2,400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (3,900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (4,1600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (5,2500000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (6,3600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (7,4900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (8,6400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (9,8100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (10,10000000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (11,12100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (12,14400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (13,16900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (14,19600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (15,22500000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (16,25600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (17,28900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (18,32400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (19,36100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (20,40000000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (21,44100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (22,48400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (23,52900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (24,57600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (25,62500000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (26,67600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (27,72900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (28,78400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (29,84100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (30,90000000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (31,96100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (32,102400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (33,108900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (34,115600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (35,122500000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (36,129600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (37,136900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (38,144400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (39,152100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (40,160000000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (41,168100000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (42,176400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (43,184900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (44,193600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (45,202500000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (46,211600000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (47,220900000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (48,230400000);
REPLACE INTO `exp_guild` (`level`,`exp`) VALUES (49,240100000);
