-- Auto-generated by Tools.RathenaImporter (const_db).
-- Source: db/const.yml
-- Rows: 6
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `const_db` (`name`,`value`,`is_parameter`) VALUES ('SWORDCLAN',1,0);
REPLACE INTO `const_db` (`name`,`value`,`is_parameter`) VALUES ('ARCWANDCLAN',2,0);
REPLACE INTO `const_db` (`name`,`value`,`is_parameter`) VALUES ('GOLDENMACECLAN',3,0);
REPLACE INTO `const_db` (`name`,`value`,`is_parameter`) VALUES ('CROSSBOWCLAN',4,0);
REPLACE INTO `const_db` (`name`,`value`,`is_parameter`) VALUES ('JUMPINGCLAN',5,0);
REPLACE INTO `const_db` (`name`,`value`,`is_parameter`) VALUES ('REPUTATION_EP18',3,0);
