-- Auto-generated by Tools.RathenaImporter (homunculus_db).
-- Source: db/re/homunculus_db.yml
-- Rows: 13
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Lif','Lif',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Lif_H');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Amistr','Amistr',NULL,NULL,NULL,'Brute',NULL,NULL,NULL,'Amistr_H');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Filir','Filir',NULL,NULL,NULL,'Brute',NULL,NULL,NULL,'Filir_H');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Vanilmirth','Vanilmirth',NULL,NULL,NULL,'Formless',NULL,NULL,NULL,'Vanilmirth_H');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Lif2','Lif',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Lif_H2');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Amistr2','Amistr',NULL,NULL,NULL,'Brute',NULL,NULL,NULL,'Amistr_H2');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Filir2','Filir',NULL,NULL,NULL,'Brute',NULL,NULL,NULL,'Filir_H2');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Vanilmirth2','Vanilmirth',NULL,NULL,NULL,'Formless',NULL,NULL,NULL,'Vanilmirth_H2');
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Eira','Eira',NULL,NULL,'Medium','Angel','Wind',NULL,NULL,NULL);
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Bayeri','Bayeri',NULL,NULL,'Medium','Brute','Holy',NULL,NULL,NULL);
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Sera','Sera',NULL,NULL,'Medium','Insect','Earth',NULL,NULL,NULL);
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Dieter','Dieter',NULL,NULL,'Medium','Formless','Fire',NULL,NULL,NULL);
REPLACE INTO `homunculus_db` (`class_aegis`,`name`,`food_item`,`hungry_delay`,`size`,`race`,`element`,`ele_level`,`attack_range`,`evolution_class`) VALUES ('Eleanor','Eleanor',NULL,NULL,'Medium',NULL,'Poison',NULL,NULL,NULL);
