-- Auto-generated by Tools.RathenaImporter (level_penalty).
-- Source: db/re/level_penalty.yml
-- Rows: 2
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `level_penalty_db` (`penalty_type`) VALUES ('Exp');
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',16,40);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',15,115);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',14,120);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',13,125);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',12,130);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',11,135);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',10,140);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',9,135);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',8,130);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',7,125);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',6,120);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',5,115);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',4,110);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',3,105);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',-6,95);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',-11,90);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',-16,85);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',-21,60);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',-26,35);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Exp',-31,10);
REPLACE INTO `level_penalty_db` (`penalty_type`) VALUES ('Drop');
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',16,50);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',13,60);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',10,70);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',7,80);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',4,90);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',-4,90);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',-7,80);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',-10,70);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',-13,60);
REPLACE INTO `level_penalty_difference_db` (`penalty_type`,`difference`,`rate`) VALUES ('Drop',-16,50);
