-- Auto-generated by Tools.RathenaImporter (reputation).
-- Source: db/re/reputation.yml
-- Rows: 4
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `reputation` (`reputation_id`,`name`,`variable`,`minimum`,`maximum`) VALUES (1,'Orc Village','RepPointsOrc',-3000,3000);
REPLACE INTO `reputation` (`reputation_id`,`name`,`variable`,`minimum`,`maximum`) VALUES (2,'Goblin Village','RepPointsGoblin',-3000,3000);
REPLACE INTO `reputation` (`reputation_id`,`name`,`variable`,`minimum`,`maximum`) VALUES (3,'Grey Wolf Village','RepPointsWolf',-5000,5000);
REPLACE INTO `reputation` (`reputation_id`,`name`,`variable`,`minimum`,`maximum`) VALUES (4,'Isgard','RepPointsIsgard',-3000,3000);
