-- Auto-generated by Tools.RathenaImporter (mercenary_skill_db).
-- Source: db/re/mercenary_db.yml
-- Rows: 44
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,0,'MER_QUICKEN',10);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,0,'MS_PARRYING',4);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,0,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,0,'MS_BOWLINGBASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,0,'MER_LEXDIVINA',3);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,0,'MER_BLESSING',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,0,'MER_TENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,0,'MER_MAGNIFICAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,0,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,0,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,0,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,0,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,0,'MS_BASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,0,'ML_BRANDISH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,0,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,0,'MER_BENEDICTION',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,0,'ML_DEVOTION',3);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,0,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,0,'ML_DEFENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,0,'MER_SCAPEGOAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2325,0,'MS_BASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2325,0,'MER_QUICKEN',10);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2326,0,'MER_BLESSING',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,0,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,0,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,0,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,0,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,0,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,0,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,0,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,0,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,0,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,0,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,0,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,0,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2937,0,'MER_INVINCIBLEOFF2',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,0,'MER_MAGNIFICAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,0,'MER_DECAGI',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,0,'MER_TENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,0,'MER_BLESSING',3);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,0,'MER_MAGNIFICAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,0,'MER_DECAGI',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,0,'MER_TENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,0,'MER_BLESSING',3);
