-- Auto-generated by Tools.RathenaImporter (size_fix).
-- Source: db/re/size_fix.yml
-- Rows: 2
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `size_fix` (`weapon`,`small`,`medium`,`large`) VALUES ('Knuckle',100,100,75);
REPLACE INTO `size_fix` (`weapon`,`small`,`medium`,`large`) VALUES ('Whip',100,100,75);
