-- Auto-generated by Tools.RathenaImporter (mercenary_skill_db).
-- Source: db/re/mercenary_db.yml
-- Rows: 44
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,1,'MER_QUICKEN',10);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,2,'MS_PARRYING',4);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,3,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2213,4,'MS_BOWLINGBASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,1,'MER_LEXDIVINA',3);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,2,'MER_BLESSING',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,3,'MER_TENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2214,4,'MER_MAGNIFICAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,1,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,2,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,3,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2215,4,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,1,'MS_BASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,2,'ML_BRANDISH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,3,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2216,4,'MER_BENEDICTION',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,1,'ML_DEVOTION',3);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,2,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,3,'ML_DEFENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2217,4,'MER_SCAPEGOAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2325,1,'MS_BASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2325,2,'MER_QUICKEN',10);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2326,1,'MER_BLESSING',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,1,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,2,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,3,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2342,4,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,1,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,2,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,3,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2345,4,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,1,'MER_CRASH',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,2,'MS_MAGNUM',5);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,3,'MER_REGAIN',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2347,4,'MER_AUTOBERSERK',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (2937,1,'MER_INVINCIBLEOFF2',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,1,'MER_MAGNIFICAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,2,'MER_DECAGI',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,3,'MER_TENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3569,4,'MER_BLESSING',3);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,1,'MER_MAGNIFICAT',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,2,'MER_DECAGI',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,3,'MER_TENDER',1);
REPLACE INTO `mercenary_skill_db` (`merc_id`,`skill_id`,`skill_aegis`,`max_level`) VALUES (3570,4,'MER_BLESSING',3);
