-- Auto-generated by Tools.RathenaImporter (guild_skill_tree).
-- Source: db/re/guild_skill_tree.yml
-- Rows: 19
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_APPROVAL',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_KAFRACONTRACT',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_KAFRACONTRACT','GD_APPROVAL',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_GUARDRESEARCH',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_GUARDRESEARCH','GD_APPROVAL',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_GUARDUP',3);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_EXTENSION',10);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_GLORYGUILD',0);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_LEADERSHIP',5);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_GLORYWOUNDS',5);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_SOULCOLD',5);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_SOULCOLD','GD_GLORYWOUNDS',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_HAWKEYES',5);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_HAWKEYES','GD_LEADERSHIP',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_BATTLEORDER',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_BATTLEORDER','GD_APPROVAL',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_BATTLEORDER','GD_EXTENSION',2);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_REGENERATION',3);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_REGENERATION','GD_APPROVAL',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_REGENERATION','GD_EXTENSION',5);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_REGENERATION','GD_BATTLEORDER',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_RESTORE',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_RESTORE','GD_REGENERATION',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_EMERGENCYCALL',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_EMERGENCYCALL','GD_APPROVAL',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_EMERGENCYCALL','GD_GUARDRESEARCH',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_EMERGENCYCALL','GD_EXTENSION',5);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_EMERGENCYCALL','GD_BATTLEORDER',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_EMERGENCYCALL','GD_REGENERATION',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_DEVELOPMENT',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_GUILD_STORAGE',5);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_GUILD_STORAGE','GD_EMERGENCYCALL',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_GUILD_STORAGE','GD_EXTENSION',10);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_GUILD_STORAGE','GD_SOULCOLD',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_GUILD_STORAGE','GD_HAWKEYES',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_CHARGESHOUT_FLAG',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_CHARGESHOUT_FLAG','GD_EMERGENCYCALL',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_CHARGESHOUT_BEATING',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_CHARGESHOUT_BEATING','GD_CHARGESHOUT_FLAG',1);
REPLACE INTO `guild_skill_tree_db` (`skill_aegis`,`max_level`) VALUES ('GD_EMERGENCY_MOVE',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_EMERGENCY_MOVE','GD_LEADERSHIP',1);
REPLACE INTO `guild_skill_tree_requirement_db` (`skill_aegis`,`required_skill_aegis`,`required_level`) VALUES ('GD_EMERGENCY_MOVE','GD_GLORYWOUNDS',1);
