-- Auto-generated by Tools.RathenaImporter (castle_db).
-- Source: db/re/castle_db.yml
-- Rows: 44
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (0,'aldeg_cas01','Neuschwanstein','Agit#aldeg_cas01','First_Edition',6,1,212,175);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (1,'aldeg_cas02','Hohenschwangau','Agit#aldeg_cas02','First_Edition',7,1,82,71);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (2,'aldeg_cas03','Nuernberg','Agit#aldeg_cas03','First_Edition',8,1,109,112);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (3,'aldeg_cas04','Wuerzburg','Agit#aldeg_cas04','First_Edition',9,1,60,116);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (4,'aldeg_cas05','Rothenburg','Agit#aldeg_cas05','First_Edition',10,1,61,185);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (5,'gefg_cas01','Repherion','Agit#gefg_cas01','First_Edition',11,1,40,43);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (6,'gefg_cas02','Eeyolbriggar','Agit#gefg_cas02','First_Edition',12,1,22,66);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (7,'gefg_cas03','Yesnelph','Agit#gefg_cas03','First_Edition',13,1,112,23);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (8,'gefg_cas04','Bergel','Agit#gefg_cas04','First_Edition',14,1,58,46);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (9,'gefg_cas05','Mersetzdeitz','Agit#gefg_cas05','First_Edition',15,1,66,48);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (10,'payg_cas01','Bright Arbor','Agit#payg_cas01','First_Edition',16,1,115,57);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (11,'payg_cas02','Scarlet Palace','Agit#payg_cas02','First_Edition',17,1,26,265);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (12,'payg_cas03','Holy Shadow','Agit#payg_cas03','First_Edition',18,1,43,264);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (13,'payg_cas04','Sacred Altar','Agit#payg_cas04','First_Edition',19,1,36,272);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (14,'payg_cas05','Bamboo Grove Hill','Agit#payg_cas05','First_Edition',20,1,274,246);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (15,'prtg_cas01','Kriemhild','Agit#prtg_cas01','First_Edition',1,1,107,180);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (16,'prtg_cas02','Swanhild','Agit#prtg_cas02','First_Edition',2,1,94,56);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (17,'prtg_cas03','Fadhgridh','Agit#prtg_cas03','First_Edition',3,1,46,97);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (18,'prtg_cas04','Skoegul','Agit#prtg_cas04','First_Edition',4,1,260,262);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (19,'prtg_cas05','Gondul','Agit#prtg_cas05','First_Edition',5,1,26,38);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (20,'nguild_alde','Earth','Agit_N01','First_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (21,'nguild_gef','Air','Agit_N02','First_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (22,'nguild_pay','Water','Agit_N03','First_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (23,'nguild_prt','Fire','Agit_N04','First_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (24,'schg_cas01','Himinn','Manager#schg_cas01','Second_Edition',26,1,233,300);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (25,'schg_cas02','Andlangr','Manager#schg_cas02','Second_Edition',27,1,101,372);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (26,'schg_cas03','Viblainn','Manager#schg_cas03','Second_Edition',28,1,81,94);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (27,'schg_cas04','Hljod','Manager#schg_cas04','Second_Edition',29,1,233,300);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (28,'schg_cas05','Skidbladnir','Manager#schg_cas05','Second_Edition',30,1,233,300);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (29,'arug_cas01','Mardol','Manager#arug_cas01','Second_Edition',21,1,77,371);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (30,'arug_cas02','Cyr','Manager#arug_cas02','Second_Edition',22,1,301,332);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (31,'arug_cas03','Horn','Manager#arug_cas03','Second_Edition',23,1,322,91);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (32,'arug_cas04','Gefn','Manager#arug_cas04','Second_Edition',24,1,322,91);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (33,'arug_cas05','Bandis','Manager#arug_cas05','Second_Edition',25,1,322,91);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (34,'te_aldecas1','Kafragarten 1','Manager_TE#Glaris','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (35,'te_aldecas2','Kafragarten 2','Manager_TE#Defolty','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (36,'te_aldecas3','Kafragarten 3','Manager_TE#Sorin','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (37,'te_aldecas4','Kafragarten 4','Manager_TE#Bennit','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (38,'te_aldecas5','Kafragarten 5','Manager_TE#W','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (39,'te_prtcas01','Gloria 1','Manager_TE#Gaebolg','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (40,'te_prtcas02','Gloria 2','Manager_TE#Richard','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (41,'te_prtcas03','Gloria 3','Manager_TE#Wigner','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (42,'te_prtcas04','Gloria 4','Manager_TE#Heine','Third_Edition',NULL,NULL,NULL,NULL);
REPLACE INTO `castle_db` (`castle_id`,`map_name`,`name`,`npc_name`,`castle_type`,`client_id`,`warp_enabled`,`warp_x`,`warp_y`) VALUES (43,'te_prtcas05','Gloria 5','Manager_TE#Nerious','Third_Edition',NULL,NULL,NULL,NULL);
