-- Auto-generated by Tools.RathenaImporter (spellbook_db).
-- Source: db/re/spellbook_db.yml
-- Rows: 10
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WZ_METEOR','WL_MB_MS',10);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WZ_VERMILION','WL_MB_LOV',10);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WZ_STORMGUST','WL_MB_SG',10);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WL_JACKFROST','WL_MB_JF',10);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WL_DRAINLIFE','WL_MB_DL',8);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WL_CRIMSONROCK','WL_MB_CR',12);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WL_COMET','WL_MB_CM',22);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WL_CHAINLIGHTNING','WL_MB_CL',12);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WL_EARTHSTRAIN','WL_MB_ES',12);
REPLACE INTO `spellbook_db` (`skill_name`,`book_name_aegis`,`preserve_points`) VALUES ('WL_TETRAVORTEX','WL_MB_TV',22);
