-- Auto-generated by Tools.RathenaImporter (achievement_level_db).
-- Source: db/re/achievement_level_db.yml
-- Rows: 20
-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.

REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (1,18);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (2,49);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (3,98);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (4,171);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (5,306);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (6,410);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (7,550);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (8,728);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (9,942);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (10,1247);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (11,1504);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (12,1804);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (13,2152);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (14,2550);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (15,3070);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (16,3522);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (17,4030);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (18,4592);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (19,5210);
REPLACE INTO `achievement_level_db` (`level`,`required_points`) VALUES (20,5980);
