// Auto-generated from rAthena dungeons/c_tower.txt.
// Re-generate with: python3 scripts/tools/import_rathena.py

registerSpawn(
    { map: "c_tower1", mobId: 1195, amount: 107, name: "Rideword" },
    { map: "c_tower1", mobId: 1199, amount: 107, name: "Punk" },
    { map: "c_tower1", mobId: 1102, amount: 1, name: "Bathory" },
    { map: "c_tower1", mobId: 1270, amount: 1, name: "Clock Tower Manager" },
    { map: "c_tower2", mobId: 1269, amount: 55, name: "Clock" },
    { map: "c_tower2", mobId: 1199, amount: 55, name: "Punk" },
    { map: "c_tower2", mobId: 1195, amount: 16, name: "Rideword" },
    { map: "c_tower2", mobId: 1191, amount: 4, name: "Mimic" },
    { map: "c_tower2", mobId: 1377, amount: 2, name: "Elder" },
    { map: "c_tower2", mobId: 1270, amount: 1, name: "Clock Tower Manager" },
    { map: "c_tower3", mobId: 1193, amount: 109, name: "Alarm" },
    { map: "c_tower3", mobId: 1191, amount: 9, name: "Mimic" },
    { map: "c_tower3", mobId: 1195, amount: 8, name: "Rideword" },
    { map: "c_tower3", mobId: 1270, amount: 4, name: "Clock Tower Manager" },
    { map: "c_tower4", mobId: 1269, amount: 35, name: "Clock" },
    { map: "c_tower4", mobId: 1320, amount: 30, name: "Owl Duke" },
    { map: "c_tower4", mobId: 1193, amount: 30, name: "Alarm" },
    { map: "c_tower4", mobId: 1195, amount: 15, name: "Rideword" },
    { map: "c_tower4", mobId: 1191, amount: 12, name: "Mimic" },
    { map: "c_tower4", mobId: 1179, amount: 5, name: "Whisper" },
    { map: "c_tower4", mobId: 1270, amount: 3, name: "Clock Tower Manager" },
    { map: "c_tower4", mobId: 1377, amount: 2, name: "Elder" },
    { map: "c_tower2_", mobId: 2479, amount: 4, name: "Mimic (Nightmare)" },
    { map: "c_tower2_", mobId: 2478, amount: 16, name: "Rideword (Nightmare)" },
    { map: "c_tower2_", mobId: 2919, amount: 55, name: "Neo Punk" },
    { map: "c_tower2_", mobId: 2916, amount: 55, name: "Big Ben" },
    { map: "c_tower2_", mobId: 2918, amount: 1, name: "Time Keeper" },
    { map: "c_tower2_", mobId: 2920, amount: 2, respawn: { baseMs: 3600000, jitterMs: 0 }, name: "Arc Elder" },
    { map: "c_tower2_", mobId: 2921, amount: 1, respawn: { baseMs: 5000, jitterMs: 1800000 }, name: "Owl Viscount" },
    { map: "c_tower3_", mobId: 2479, amount: 9, name: "Mimic (Nightmare)" },
    { map: "c_tower3_", mobId: 2478, amount: 8, name: "Rideword (Nightmare)" },
    { map: "c_tower3_", mobId: 2917, amount: 109, name: "Big Bell" },
    { map: "c_tower3_", mobId: 2918, amount: 2, name: "Time Keeper" },
    { map: "c_tower3_", mobId: 2921, amount: 3, respawn: { baseMs: 5000, jitterMs: 1800000 }, name: "Owl Viscount" },
    { map: "c_tower3_", mobId: 2923, amount: 3, respawn: { baseMs: 5000, jitterMs: 5000 }, name: "Owl Marquis" },
    { map: "c_tower3_", mobId: 3074, amount: 1, respawn: { baseMs: 7200000, jitterMs: 0 }, boss: true, name: "Time Holder" },
);
