namespace Map.Server.Status;

/// <summary>
/// Mirror of rAthena's <c>enum sc_type</c>
/// (<c>rathena/src/map/status.hpp:233</c>). Values are in lockstep with
/// rAthena indices so persistence
/// (<c>SaveStatusChangeDataAsync</c> / <c>RequestStatusChangeDataAsync</c>)
/// can round-trip without remapping. Friendly C#-side aliases live at
/// the bottom of the enum below the rAthena range (≥ 2000).
/// </summary>
/// <remarks>
/// Names are <c>SC_FOO_BAR</c> → <c>FooBar</c> PascalCase. A handful of
/// overrides keep our pre-existing port-friendly names
/// (<c>DeadlyPoison</c>, <c>IncreaseAgi</c>, <c>DecreaseAgi</c>,
/// <c>Concentrate</c>, <c>BasilicaCell</c>).
///
/// The companion behavior table lives in
/// <see cref="StatusEffectRegistry"/>. Most SCs are pure data carriers
/// (duration + stat delta); a handful (Poison, Bleeding, Burning,
/// Endure, Maximize, Suffragium, Memorize, Slowcast, …) need real
/// per-tick or per-cast hooks — those land in T2.4b.
/// </remarks>
public enum StatusType : short
{
    None = -1,
    Stone,  // SC_STONE
    Freeze,  // SC_FREEZE
    Stun,  // SC_STUN
    Sleep,  // SC_SLEEP
    Poison,  // SC_POISON
    Curse,  // SC_CURSE
    Silence,  // SC_SILENCE
    Confusion,  // SC_CONFUSION
    Blind,  // SC_BLIND
    Bleeding,  // SC_BLEEDING
    DeadlyPoison,  // SC_DPOISON
    Stonewait,  // SC_STONEWAIT
    Provoke = 20,  // SC_PROVOKE
    Endure,  // SC_ENDURE
    Twohandquicken,  // SC_TWOHANDQUICKEN
    Concentrate,  // SC_CONCENTRATE
    Hiding,  // SC_HIDING
    Cloaking,  // SC_CLOAKING
    Encpoison,  // SC_ENCPOISON
    Poisonreact,  // SC_POISONREACT
    Quagmire,  // SC_QUAGMIRE
    Angelus,  // SC_ANGELUS
    Blessing,  // SC_BLESSING
    Signumcrucis,  // SC_SIGNUMCRUCIS
    IncreaseAgi,  // SC_INCREASEAGI
    DecreaseAgi,  // SC_DECREASEAGI
    Slowpoison,  // SC_SLOWPOISON
    Impositio,  // SC_IMPOSITIO
    Suffragium,  // SC_SUFFRAGIUM
    Aspersio,  // SC_ASPERSIO
    Benedictio,  // SC_BENEDICTIO
    Kyrie,  // SC_KYRIE
    Magnificat,  // SC_MAGNIFICAT
    Gloria,  // SC_GLORIA
    Aeterna,  // SC_AETERNA
    Adrenaline,  // SC_ADRENALINE
    Weaponperfection,  // SC_WEAPONPERFECTION
    Overthrust,  // SC_OVERTHRUST
    Maximizepower,  // SC_MAXIMIZEPOWER
    Trickdead,  // SC_TRICKDEAD
    Loud,  // SC_LOUD
    Energycoat,  // SC_ENERGYCOAT
    Brokenarmor,  // SC_BROKENARMOR
    Brokenweapon,  // SC_BROKENWEAPON
    Hallucination,  // SC_HALLUCINATION
    Weight50,  // SC_WEIGHT50
    Weight90,  // SC_WEIGHT90
    Aspdpotion0,  // SC_ASPDPOTION0
    Aspdpotion1,  // SC_ASPDPOTION1
    Aspdpotion2,  // SC_ASPDPOTION2
    Aspdpotion3,  // SC_ASPDPOTION3
    Speedup0,  // SC_SPEEDUP0
    Speedup1,  // SC_SPEEDUP1
    Atkpotion,  // SC_ATKPOTION
    Matkpotion,  // SC_MATKPOTION
    Wedding,  // SC_WEDDING
    Slowdown,  // SC_SLOWDOWN
    Ankle,  // SC_ANKLE
    Keeping,  // SC_KEEPING
    Barrier,  // SC_BARRIER
    Stripweapon,  // SC_STRIPWEAPON
    Stripshield,  // SC_STRIPSHIELD
    Striparmor,  // SC_STRIPARMOR
    Striphelm,  // SC_STRIPHELM
    CpWeapon,  // SC_CP_WEAPON
    CpShield,  // SC_CP_SHIELD
    CpArmor,  // SC_CP_ARMOR
    CpHelm,  // SC_CP_HELM
    Autoguard,  // SC_AUTOGUARD
    Reflectshield,  // SC_REFLECTSHIELD
    Splasher,  // SC_SPLASHER
    Providence,  // SC_PROVIDENCE
    Defender,  // SC_DEFENDER
    Magicrod,  // SC_MAGICROD
    Spellbreaker,  // SC_SPELLBREAKER
    Autospell,  // SC_AUTOSPELL
    Sighttrasher,  // SC_SIGHTTRASHER
    Autoberserk,  // SC_AUTOBERSERK
    Spearquicken,  // SC_SPEARQUICKEN
    Autocounter,  // SC_AUTOCOUNTER
    Sight,  // SC_SIGHT
    Safetywall,  // SC_SAFETYWALL
    Ruwach,  // SC_RUWACH
    Extremityfist,  // SC_EXTREMITYFIST
    Explosionspirits,  // SC_EXPLOSIONSPIRITS
    Combo,  // SC_COMBO
    BladestopWait,  // SC_BLADESTOP_WAIT
    Bladestop,  // SC_BLADESTOP
    Fireweapon,  // SC_FIREWEAPON
    Waterweapon,  // SC_WATERWEAPON
    Windweapon,  // SC_WINDWEAPON
    Earthweapon,  // SC_EARTHWEAPON
    Volcano,  // SC_VOLCANO
    Deluge,  // SC_DELUGE
    Violentgale,  // SC_VIOLENTGALE
    WatkElement,  // SC_WATK_ELEMENT
    Armor,  // SC_ARMOR
    ArmorElementWater,  // SC_ARMOR_ELEMENT_WATER
    Nochat,  // SC_NOCHAT
    Protectexp,  // SC_PROTECTEXP
    Aurablade,  // SC_AURABLADE
    Parrying,  // SC_PARRYING
    Concentration,  // SC_CONCENTRATION
    Tensionrelax,  // SC_TENSIONRELAX
    Berserk,  // SC_BERSERK
    Fury,  // SC_FURY
    Gospel,  // SC_GOSPEL
    Assumptio,  // SC_ASSUMPTIO
    Basilica,  // SC_BASILICA
    Guildaura,  // SC_GUILDAURA
    Magicpower,  // SC_MAGICPOWER
    Edp,  // SC_EDP
    Truesight,  // SC_TRUESIGHT
    Windwalk,  // SC_WINDWALK
    Meltdown,  // SC_MELTDOWN
    Cartboost,  // SC_CARTBOOST
    Chasewalk,  // SC_CHASEWALK
    Rejectsword,  // SC_REJECTSWORD
    Marionette,  // SC_MARIONETTE
    Marionette2,  // SC_MARIONETTE2
    Changeundead,  // SC_CHANGEUNDEAD
    Jointbeat,  // SC_JOINTBEAT
    Mindbreaker,  // SC_MINDBREAKER
    Memorize,  // SC_MEMORIZE
    Fogwall,  // SC_FOGWALL
    Spiderweb,  // SC_SPIDERWEB
    Devotion,  // SC_DEVOTION
    Sacrifice,  // SC_SACRIFICE
    Steelbody,  // SC_STEELBODY
    Orcish,  // SC_ORCISH
    Readystorm,  // SC_READYSTORM
    Readydown,  // SC_READYDOWN
    Readyturn,  // SC_READYTURN
    Readycounter,  // SC_READYCOUNTER
    Dodge,  // SC_DODGE
    Run,  // SC_RUN
    Shadowweapon,  // SC_SHADOWWEAPON
    Adrenaline2,  // SC_ADRENALINE2
    Ghostweapon,  // SC_GHOSTWEAPON
    Kaizel,  // SC_KAIZEL
    Kaahi,  // SC_KAAHI
    Kaupe,  // SC_KAUPE
    Onehand,  // SC_ONEHAND
    Preserve,  // SC_PRESERVE
    Battleorders,  // SC_BATTLEORDERS
    Regeneration,  // SC_REGENERATION
    Doublecast,  // SC_DOUBLECAST
    Gravitation,  // SC_GRAVITATION
    Maxoverthrust,  // SC_MAXOVERTHRUST
    Longing,  // SC_LONGING
    Hermode,  // SC_HERMODE
    Shrink,  // SC_SHRINK
    Sightblaster,  // SC_SIGHTBLASTER
    Winkcharm,  // SC_WINKCHARM
    Closeconfine,  // SC_CLOSECONFINE
    Closeconfine2,  // SC_CLOSECONFINE2
    Dancing,  // SC_DANCING
    Elementalchange,  // SC_ELEMENTALCHANGE
    Richmankim,  // SC_RICHMANKIM
    Eternalchaos,  // SC_ETERNALCHAOS
    Drumbattle,  // SC_DRUMBATTLE
    Nibelungen,  // SC_NIBELUNGEN
    Rokisweil,  // SC_ROKISWEIL
    Intoabyss,  // SC_INTOABYSS
    Siegfried,  // SC_SIEGFRIED
    Whistle,  // SC_WHISTLE
    Assncros,  // SC_ASSNCROS
    Poembragi,  // SC_POEMBRAGI
    Appleidun,  // SC_APPLEIDUN
    Modechange,  // SC_MODECHANGE
    Humming,  // SC_HUMMING
    Dontforgetme,  // SC_DONTFORGETME
    Fortune,  // SC_FORTUNE
    Service4u,  // SC_SERVICE4U
    Stop,  // SC_STOP
    Spurt,  // SC_SPURT
    Spirit,  // SC_SPIRIT
    Coma,  // SC_COMA
    Intravision,  // SC_INTRAVISION
    Incallstatus,  // SC_INCALLSTATUS
    Incstr,  // SC_INCSTR
    Incagi,  // SC_INCAGI
    Incvit,  // SC_INCVIT
    Incint,  // SC_INCINT
    Incdex,  // SC_INCDEX
    Incluk,  // SC_INCLUK
    Inchit,  // SC_INCHIT
    Inchitrate,  // SC_INCHITRATE
    Incflee,  // SC_INCFLEE
    Incfleerate,  // SC_INCFLEERATE
    Incmhprate,  // SC_INCMHPRATE
    Incmsprate,  // SC_INCMSPRATE
    Incatkrate,  // SC_INCATKRATE
    Incmatkrate,  // SC_INCMATKRATE
    Incdefrate,  // SC_INCDEFRATE
    Strfood,  // SC_STRFOOD
    Agifood,  // SC_AGIFOOD
    Vitfood,  // SC_VITFOOD
    Intfood,  // SC_INTFOOD
    Dexfood,  // SC_DEXFOOD
    Lukfood,  // SC_LUKFOOD
    Hitfood,  // SC_HITFOOD
    Fleefood,  // SC_FLEEFOOD
    Batkfood,  // SC_BATKFOOD
    Watkfood,  // SC_WATKFOOD
    Matkfood,  // SC_MATKFOOD
    Scresist,  // SC_SCRESIST
    Xmas,  // SC_XMAS
    Warm,  // SC_WARM
    SunComfort,  // SC_SUN_COMFORT
    MoonComfort,  // SC_MOON_COMFORT
    StarComfort,  // SC_STAR_COMFORT
    Fusion,  // SC_FUSION
    SkillrateUp,  // SC_SKILLRATE_UP
    Ske,  // SC_SKE
    Kaite,  // SC_KAITE
    Swoo,  // SC_SWOO
    Ska,  // SC_SKA
    Earthscroll,  // SC_EARTHSCROLL
    Miracle,  // SC_MIRACLE
    Madnesscancel,  // SC_MADNESSCANCEL
    Adjustment,  // SC_ADJUSTMENT
    Increasing,  // SC_INCREASING
    Gatlingfever,  // SC_GATLINGFEVER
    Tatamigaeshi,  // SC_TATAMIGAESHI
    Utsusemi,  // SC_UTSUSEMI
    Bunsinjyutsu,  // SC_BUNSINJYUTSU
    Kaensin,  // SC_KAENSIN
    Suiton,  // SC_SUITON
    Nen,  // SC_NEN
    Knowledge,  // SC_KNOWLEDGE
    Sma,  // SC_SMA
    Fling,  // SC_FLING
    Avoid,  // SC_AVOID
    Change,  // SC_CHANGE
    Bloodlust,  // SC_BLOODLUST
    Fleet,  // SC_FLEET
    Speed,  // SC_SPEED
    Defence,  // SC_DEFENCE
    Incaspdrate,  // SC_INCASPDRATE
    Incflee2,  // SC_INCFLEE2
    Jailed,  // SC_JAILED
    Enchantarms,  // SC_ENCHANTARMS
    Magicalattack,  // SC_MAGICALATTACK
    Armorchange,  // SC_ARMORCHANGE
    Criticalwound,  // SC_CRITICALWOUND
    Magicmirror,  // SC_MAGICMIRROR
    Slowcast,  // SC_SLOWCAST
    Summer,  // SC_SUMMER
    Expboost,  // SC_EXPBOOST
    Itemboost,  // SC_ITEMBOOST
    Bossmapinfo,  // SC_BOSSMAPINFO
    Lifeinsurance,  // SC_LIFEINSURANCE
    Inccri,  // SC_INCCRI
    MdefRate = 265,  // SC_MDEF_RATE
    Inchealrate = 267,  // SC_INCHEALRATE
    Pneuma,  // SC_PNEUMA
    Autotrade,  // SC_AUTOTRADE
    Ksprotected,  // SC_KSPROTECTED
    ArmorResist,  // SC_ARMOR_RESIST
    SpcostRate,  // SC_SPCOST_RATE
    CommonscResist,  // SC_COMMONSC_RESIST
    Sevenwind,  // SC_SEVENWIND
    DefRate,  // SC_DEF_RATE
    Walkspeed = 277,  // SC_WALKSPEED
    MercFleeup,  // SC_MERC_FLEEUP
    MercAtkup,  // SC_MERC_ATKUP
    MercHpup,  // SC_MERC_HPUP
    MercSpup,  // SC_MERC_SPUP
    MercHitup,  // SC_MERC_HITUP
    MercQuicken,  // SC_MERC_QUICKEN
    Rebirth,  // SC_REBIRTH
    Itemscript = 289,  // SC_ITEMSCRIPT
    SLifepotion,  // SC_S_LIFEPOTION
    LLifepotion,  // SC_L_LIFEPOTION
    Jexpboost,  // SC_JEXPBOOST
    Hellpower = 294,  // SC_HELLPOWER
    Invincible,  // SC_INVINCIBLE
    ManuAtk = 297,  // SC_MANU_ATK
    ManuDef,  // SC_MANU_DEF
    SplAtk,  // SC_SPL_ATK
    SplDef,  // SC_SPL_DEF
    ManuMatk,  // SC_MANU_MATK
    SplMatk,  // SC_SPL_MATK
    FoodStrCash,  // SC_FOOD_STR_CASH
    FoodAgiCash,  // SC_FOOD_AGI_CASH
    FoodVitCash,  // SC_FOOD_VIT_CASH
    FoodDexCash,  // SC_FOOD_DEX_CASH
    FoodIntCash,  // SC_FOOD_INT_CASH
    FoodLukCash,  // SC_FOOD_LUK_CASH
    Fear,  // SC_FEAR
    Burning,  // SC_BURNING
    Freezing,  // SC_FREEZING
    Enchantblade,  // SC_ENCHANTBLADE
    Deathbound,  // SC_DEATHBOUND
    Millenniumshield,  // SC_MILLENNIUMSHIELD
    Crushstrike,  // SC_CRUSHSTRIKE
    Refresh,  // SC_REFRESH
    ReuseRefresh,  // SC_REUSE_REFRESH
    Giantgrowth,  // SC_GIANTGROWTH
    Stonehardskin,  // SC_STONEHARDSKIN
    Vitalityactivation,  // SC_VITALITYACTIVATION
    Stormblast,  // SC_STORMBLAST
    Fightingspirit,  // SC_FIGHTINGSPIRIT
    Abundance,  // SC_ABUNDANCE
    Adoramus,  // SC_ADORAMUS
    Epiclesis,  // SC_EPICLESIS
    Oratio,  // SC_ORATIO
    Laudaagnus,  // SC_LAUDAAGNUS
    Laudaramus,  // SC_LAUDARAMUS
    Renovatio,  // SC_RENOVATIO
    Expiatio,  // SC_EXPIATIO
    Duplelight,  // SC_DUPLELIGHT
    Secrament,  // SC_SECRAMENT
    Whiteimprison,  // SC_WHITEIMPRISON
    Marshofabyss,  // SC_MARSHOFABYSS
    Recognizedspell,  // SC_RECOGNIZEDSPELL
    Stasis,  // SC_STASIS
    Sphere1,  // SC_SPHERE_1
    Sphere2,  // SC_SPHERE_2
    Sphere3,  // SC_SPHERE_3
    Sphere4,  // SC_SPHERE_4
    Sphere5,  // SC_SPHERE_5
    ReadingSb,  // SC_READING_SB
    FreezeSp,  // SC_FREEZE_SP
    Fearbreeze,  // SC_FEARBREEZE
    Electricshocker,  // SC_ELECTRICSHOCKER
    Wugdash,  // SC_WUGDASH
    Bite,  // SC_BITE
    Camouflage,  // SC_CAMOUFLAGE
    Acceleration,  // SC_ACCELERATION
    Hovering,  // SC_HOVERING
    Shapeshift,  // SC_SHAPESHIFT
    Infraredscan,  // SC_INFRAREDSCAN
    Analyze,  // SC_ANALYZE
    Magneticfield,  // SC_MAGNETICFIELD
    Neutralbarrier,  // SC_NEUTRALBARRIER
    NeutralbarrierMaster,  // SC_NEUTRALBARRIER_MASTER
    Stealthfield,  // SC_STEALTHFIELD
    StealthfieldMaster,  // SC_STEALTHFIELD_MASTER
    Overheat,  // SC_OVERHEAT
    OverheatLimitpoint,  // SC_OVERHEAT_LIMITPOINT
    Venomimpress,  // SC_VENOMIMPRESS
    Poisoningweapon,  // SC_POISONINGWEAPON
    Weaponblocking,  // SC_WEAPONBLOCKING
    Cloakingexceed,  // SC_CLOAKINGEXCEED
    Hallucinationwalk,  // SC_HALLUCINATIONWALK
    HallucinationwalkPostdelay,  // SC_HALLUCINATIONWALK_POSTDELAY
    Rollingcutter,  // SC_ROLLINGCUTTER
    Toxin,  // SC_TOXIN
    Paralyse,  // SC_PARALYSE
    Venombleed,  // SC_VENOMBLEED
    Magicmushroom,  // SC_MAGICMUSHROOM
    Deathhurt,  // SC_DEATHHURT
    Pyrexia,  // SC_PYREXIA
    Oblivioncurse,  // SC_OBLIVIONCURSE
    Leechesend,  // SC_LEECHESEND
    Reflectdamage,  // SC_REFLECTDAMAGE
    Forceofvanguard,  // SC_FORCEOFVANGUARD
    ShieldspellHp,  // SC_SHIELDSPELL_HP
    ShieldspellSp,  // SC_SHIELDSPELL_SP
    ShieldspellAtk,  // SC_SHIELDSPELL_ATK
    Exeedbreak,  // SC_EXEEDBREAK
    Prestige,  // SC_PRESTIGE
    Banding,  // SC_BANDING
    BandingDefence,  // SC_BANDING_DEFENCE
    Earthdrive,  // SC_EARTHDRIVE
    Inspiration,  // SC_INSPIRATION
    Spellfist,  // SC_SPELLFIST
    Crystalize,  // SC_CRYSTALIZE
    Striking,  // SC_STRIKING
    Warmer,  // SC_WARMER
    VacuumExtreme,  // SC_VACUUM_EXTREME
    Propertywalk,  // SC_PROPERTYWALK
    Swingdance,  // SC_SWINGDANCE
    Symphonyoflover,  // SC_SYMPHONYOFLOVER
    Moonlitserenade,  // SC_MOONLITSERENADE
    Rushwindmill,  // SC_RUSHWINDMILL
    Echosong,  // SC_ECHOSONG
    Harmonize,  // SC_HARMONIZE
    Voiceofsiren,  // SC_VOICEOFSIREN
    Deepsleep,  // SC_DEEPSLEEP
    Sircleofnature,  // SC_SIRCLEOFNATURE
    Gloomyday,  // SC_GLOOMYDAY
    GloomydaySk,  // SC_GLOOMYDAY_SK
    Songofmana,  // SC_SONGOFMANA
    Dancewithwug,  // SC_DANCEWITHWUG
    Saturdaynightfever,  // SC_SATURDAYNIGHTFEVER
    Leradsdew,  // SC_LERADSDEW
    Melodyofsink,  // SC_MELODYOFSINK
    Beyondofwarcry,  // SC_BEYONDOFWARCRY
    Unlimitedhummingvoice,  // SC_UNLIMITEDHUMMINGVOICE
    SitdownForce,  // SC_SITDOWN_FORCE
    Netherworld,  // SC_NETHERWORLD
    Crescentelbow,  // SC_CRESCENTELBOW
    CursedcircleAtker,  // SC_CURSEDCIRCLE_ATKER
    CursedcircleTarget,  // SC_CURSEDCIRCLE_TARGET
    Lightningwalk,  // SC_LIGHTNINGWALK
    Raisingdragon,  // SC_RAISINGDRAGON
    GtEnergygain,  // SC_GT_ENERGYGAIN
    GtChange,  // SC_GT_CHANGE
    GtRevitalize,  // SC_GT_REVITALIZE
    GnCartboost,  // SC_GN_CARTBOOST
    Thornstrap,  // SC_THORNSTRAP
    Bloodsucker,  // SC_BLOODSUCKER
    Smokepowder,  // SC_SMOKEPOWDER
    Teargas,  // SC_TEARGAS
    Mandragora,  // SC_MANDRAGORA
    Stomachache,  // SC_STOMACHACHE
    MysteriousPowder,  // SC_MYSTERIOUS_POWDER
    MelonBomb,  // SC_MELON_BOMB
    BananaBomb,  // SC_BANANA_BOMB
    BananaBombSitdown,  // SC_BANANA_BOMB_SITDOWN
    SavageSteak,  // SC_SAVAGE_STEAK
    CocktailWargBlood,  // SC_COCKTAIL_WARG_BLOOD
    MinorBbq,  // SC_MINOR_BBQ
    SiromaIceTea,  // SC_SIROMA_ICE_TEA
    DroceraHerbSteamed,  // SC_DROCERA_HERB_STEAMED
    PuttiTailsNoodles,  // SC_PUTTI_TAILS_NOODLES
    Boost500,  // SC_BOOST500
    FullSwingK,  // SC_FULL_SWING_K
    ManaPlus,  // SC_MANA_PLUS
    MustleM,  // SC_MUSTLE_M
    LifeForceF,  // SC_LIFE_FORCE_F
    ExtractWhitePotionZ,  // SC_EXTRACT_WHITE_POTION_Z
    Vitata500,  // SC_VITATA_500
    ExtractSalamineJuice,  // SC_EXTRACT_SALAMINE_JUICE
    Reproduce,  // SC__REPRODUCE
    Autoshadowspell,  // SC__AUTOSHADOWSPELL
    Shadowform,  // SC__SHADOWFORM
    Bodypaint,  // SC__BODYPAINT
    Invisibility,  // SC__INVISIBILITY
    Deadlyinfect,  // SC__DEADLYINFECT
    Enervation,  // SC__ENERVATION
    Groomy,  // SC__GROOMY
    Ignorance,  // SC__IGNORANCE
    Laziness,  // SC__LAZINESS
    Unlucky,  // SC__UNLUCKY
    Weakness,  // SC__WEAKNESS
    Stripaccessory,  // SC__STRIPACCESSORY
    Manhole,  // SC__MANHOLE
    Bloodylust,  // SC__BLOODYLUST
    CircleOfFire,  // SC_CIRCLE_OF_FIRE
    CircleOfFireOption,  // SC_CIRCLE_OF_FIRE_OPTION
    FireCloak,  // SC_FIRE_CLOAK
    FireCloakOption,  // SC_FIRE_CLOAK_OPTION
    WaterScreen,  // SC_WATER_SCREEN
    WaterScreenOption,  // SC_WATER_SCREEN_OPTION
    WaterDrop,  // SC_WATER_DROP
    WaterDropOption,  // SC_WATER_DROP_OPTION
    WaterBarrier,  // SC_WATER_BARRIER
    WindStep,  // SC_WIND_STEP
    WindStepOption,  // SC_WIND_STEP_OPTION
    WindCurtain,  // SC_WIND_CURTAIN
    WindCurtainOption,  // SC_WIND_CURTAIN_OPTION
    Zephyr,  // SC_ZEPHYR
    SolidSkin,  // SC_SOLID_SKIN
    SolidSkinOption,  // SC_SOLID_SKIN_OPTION
    StoneShield,  // SC_STONE_SHIELD
    StoneShieldOption,  // SC_STONE_SHIELD_OPTION
    PowerOfGaia,  // SC_POWER_OF_GAIA
    Pyrotechnic,  // SC_PYROTECHNIC
    PyrotechnicOption,  // SC_PYROTECHNIC_OPTION
    Heater,  // SC_HEATER
    HeaterOption,  // SC_HEATER_OPTION
    Tropic,  // SC_TROPIC
    TropicOption,  // SC_TROPIC_OPTION
    Aquaplay,  // SC_AQUAPLAY
    AquaplayOption,  // SC_AQUAPLAY_OPTION
    Cooler,  // SC_COOLER
    CoolerOption,  // SC_COOLER_OPTION
    ChillyAir,  // SC_CHILLY_AIR
    ChillyAirOption,  // SC_CHILLY_AIR_OPTION
    Gust,  // SC_GUST
    GustOption,  // SC_GUST_OPTION
    Blast,  // SC_BLAST
    BlastOption,  // SC_BLAST_OPTION
    WildStorm,  // SC_WILD_STORM
    WildStormOption,  // SC_WILD_STORM_OPTION
    Petrology,  // SC_PETROLOGY
    PetrologyOption,  // SC_PETROLOGY_OPTION
    CursedSoil,  // SC_CURSED_SOIL
    CursedSoilOption,  // SC_CURSED_SOIL_OPTION
    Upheaval,  // SC_UPHEAVAL
    UpheavalOption,  // SC_UPHEAVAL_OPTION
    TidalWeapon,  // SC_TIDAL_WEAPON
    TidalWeaponOption,  // SC_TIDAL_WEAPON_OPTION
    RockCrusher,  // SC_ROCK_CRUSHER
    RockCrusherAtk,  // SC_ROCK_CRUSHER_ATK
    Leadership,  // SC_LEADERSHIP
    Glorywounds,  // SC_GLORYWOUNDS
    Soulcold,  // SC_SOULCOLD
    Hawkeyes,  // SC_HAWKEYES
    OdinsPower,  // SC_ODINS_POWER
    Raid,  // SC_RAID
    FireInsignia,  // SC_FIRE_INSIGNIA
    WaterInsignia,  // SC_WATER_INSIGNIA
    WindInsignia,  // SC_WIND_INSIGNIA
    EarthInsignia,  // SC_EARTH_INSIGNIA
    PushCart,  // SC_PUSH_CART
    Spellbook1,  // SC_SPELLBOOK1
    Spellbook2,  // SC_SPELLBOOK2
    Spellbook3,  // SC_SPELLBOOK3
    Spellbook4,  // SC_SPELLBOOK4
    Spellbook5,  // SC_SPELLBOOK5
    Spellbook6,  // SC_SPELLBOOK6
    Maxspellbook,  // SC_MAXSPELLBOOK
    Incmhp,  // SC_INCMHP
    Incmsp,  // SC_INCMSP
    Partyflee,  // SC_PARTYFLEE
    Meikyousisui,  // SC_MEIKYOUSISUI
    Jyumonjikiri,  // SC_JYUMONJIKIRI
    Kyougaku,  // SC_KYOUGAKU
    Izayoi,  // SC_IZAYOI
    Zenkai,  // SC_ZENKAI
    Kagehumi,  // SC_KAGEHUMI
    Kyomu,  // SC_KYOMU
    Kagemusya,  // SC_KAGEMUSYA
    Zangetsu,  // SC_ZANGETSU
    Gensou,  // SC_GENSOU
    Akaitsuki,  // SC_AKAITSUKI
    StyleChange,  // SC_STYLE_CHANGE
    TinderBreaker,  // SC_TINDER_BREAKER
    TinderBreaker2,  // SC_TINDER_BREAKER2
    Cbc,  // SC_CBC
    Eqc,  // SC_EQC
    GoldeneFerse,  // SC_GOLDENE_FERSE
    AngriffsModus,  // SC_ANGRIFFS_MODUS
    OveredBoost,  // SC_OVERED_BOOST
    LightOfRegene,  // SC_LIGHT_OF_REGENE
    Ash,  // SC_ASH
    GraniticArmor,  // SC_GRANITIC_ARMOR
    MagmaFlow,  // SC_MAGMA_FLOW
    Pyroclastic,  // SC_PYROCLASTIC
    Paralysis,  // SC_PARALYSIS
    PainKiller,  // SC_PAIN_KILLER
    Hanbok,  // SC_HANBOK
    Defset,  // SC_DEFSET
    Mdefset,  // SC_MDEFSET
    Darkcrow,  // SC_DARKCROW
    FullThrottle,  // SC_FULL_THROTTLE
    Rebound,  // SC_REBOUND
    Unlimit,  // SC_UNLIMIT
    KingsGrace,  // SC_KINGS_GRACE
    TelekinesisIntense,  // SC_TELEKINESIS_INTENSE
    Offertorium,  // SC_OFFERTORIUM
    FriggSong,  // SC_FRIGG_SONG
    MonsterTransform,  // SC_MONSTER_TRANSFORM
    AngelProtect,  // SC_ANGEL_PROTECT
    Illusiondoping,  // SC_ILLUSIONDOPING
    Flashcombo,  // SC_FLASHCOMBO
    Moonstar,  // SC_MOONSTAR
    SuperStar,  // SC_SUPER_STAR
    HeatBarrel,  // SC_HEAT_BARREL
    Magicalbullet,  // SC_MAGICALBULLET
    PAlter,  // SC_P_ALTER
    EChain,  // SC_E_CHAIN
    CMarker,  // SC_C_MARKER
    AntiMBlast,  // SC_ANTI_M_BLAST
    BTrap,  // SC_B_TRAP
    HMine,  // SC_H_MINE
    QdShotReady,  // SC_QD_SHOT_READY
    MtfAspd,  // SC_MTF_ASPD
    MtfRangeatk,  // SC_MTF_RANGEATK
    MtfMatk,  // SC_MTF_MATK
    MtfMleatked,  // SC_MTF_MLEATKED
    MtfCridamage,  // SC_MTF_CRIDAMAGE
    Oktoberfest,  // SC_OKTOBERFEST
    Strangelights,  // SC_STRANGELIGHTS
    DecorationOfMusic,  // SC_DECORATION_OF_MUSIC
    QuestBuff1,  // SC_QUEST_BUFF1
    QuestBuff2,  // SC_QUEST_BUFF2
    QuestBuff3,  // SC_QUEST_BUFF3
    AllRiding,  // SC_ALL_RIDING
    TeargasSob,  // SC_TEARGAS_SOB
    Feintbomb,  // SC__FEINTBOMB
    Chaos,  // SC__CHAOS
    Chasewalk2,  // SC_CHASEWALK2
    VacuumExtremePostdelay,  // SC_VACUUM_EXTREME_POSTDELAY
    MtfAspd2,  // SC_MTF_ASPD2
    MtfRangeatk2,  // SC_MTF_RANGEATK2
    MtfMatk2,  // SC_MTF_MATK2
    Rwc2011Scroll,  // SC_2011RWC_SCROLL
    JpEvent04,  // SC_JP_EVENT04
    MtfMhp,  // SC_MTF_MHP
    MtfMsp,  // SC_MTF_MSP
    MtfPumpkin,  // SC_MTF_PUMPKIN
    MtfHitflee,  // SC_MTF_HITFLEE
    Crifood,  // SC_CRIFOOD
    AtthasteCash,  // SC_ATTHASTE_CASH
    ReuseLimitA,  // SC_REUSE_LIMIT_A
    ReuseLimitB,  // SC_REUSE_LIMIT_B
    ReuseLimitC,  // SC_REUSE_LIMIT_C
    ReuseLimitD,  // SC_REUSE_LIMIT_D
    ReuseLimitE,  // SC_REUSE_LIMIT_E
    ReuseLimitF,  // SC_REUSE_LIMIT_F
    ReuseLimitG,  // SC_REUSE_LIMIT_G
    ReuseLimitH,  // SC_REUSE_LIMIT_H
    ReuseLimitMtf,  // SC_REUSE_LIMIT_MTF
    ReuseLimitAspdPotion,  // SC_REUSE_LIMIT_ASPD_POTION
    ReuseMillenniumshield,  // SC_REUSE_MILLENNIUMSHIELD
    ReuseCrushstrike,  // SC_REUSE_CRUSHSTRIKE
    ReuseStormblast,  // SC_REUSE_STORMBLAST
    AllRidingReuseLimit,  // SC_ALL_RIDING_REUSE_LIMIT
    ReuseLimitEcl,  // SC_REUSE_LIMIT_ECL
    ReuseLimitRecall,  // SC_REUSE_LIMIT_RECALL
    PromoteHealthReserch,  // SC_PROMOTE_HEALTH_RESERCH
    EnergyDrinkReserch,  // SC_ENERGY_DRINK_RESERCH
    NorecoverState,  // SC_NORECOVER_STATE
    Suhide,  // SC_SUHIDE
    SuStoop,  // SC_SU_STOOP
    Spritemable,  // SC_SPRITEMABLE
    Catnippowder,  // SC_CATNIPPOWDER
    SvRoottwist,  // SC_SV_ROOTTWIST
    Bitescar,  // SC_BITESCAR
    Arclousedash,  // SC_ARCLOUSEDASH
    Tunaparty,  // SC_TUNAPARTY
    Shrimp,  // SC_SHRIMP
    Freshshrimp,  // SC_FRESHSHRIMP
    ActiveMonsterTransform,  // SC_ACTIVE_MONSTER_TRANSFORM
    CloudKill,  // SC_CLOUD_KILL
    Ljosalfar,  // SC_LJOSALFAR
    MermaidLonging,  // SC_MERMAID_LONGING
    HatEffect,  // SC_HAT_EFFECT
    Flowersmoke,  // SC_FLOWERSMOKE
    Fstone,  // SC_FSTONE
    HappinessStar,  // SC_HAPPINESS_STAR
    MapleFalls,  // SC_MAPLE_FALLS
    TimeAccessory,  // SC_TIME_ACCESSORY
    MagicalFeather,  // SC_MAGICAL_FEATHER
    GvgGiant,  // SC_GVG_GIANT
    GvgGolem,  // SC_GVG_GOLEM
    GvgStun,  // SC_GVG_STUN
    GvgStone,  // SC_GVG_STONE
    GvgFreez,  // SC_GVG_FREEZ
    GvgSleep,  // SC_GVG_SLEEP
    GvgCurse,  // SC_GVG_CURSE
    GvgSilence,  // SC_GVG_SILENCE
    GvgBlind,  // SC_GVG_BLIND
    ClanInfo,  // SC_CLAN_INFO
    Swordclan,  // SC_SWORDCLAN
    Arcwandclan,  // SC_ARCWANDCLAN
    Goldenmaceclan,  // SC_GOLDENMACECLAN
    Crossbowclan,  // SC_CROSSBOWCLAN
    Jumpingclan,  // SC_JUMPINGCLAN
    Tarotcard,  // SC_TAROTCARD
    GeffenMagic1,  // SC_GEFFEN_MAGIC1
    GeffenMagic2,  // SC_GEFFEN_MAGIC2
    GeffenMagic3,  // SC_GEFFEN_MAGIC3
    Maxpain,  // SC_MAXPAIN
    ArmorElementEarth,  // SC_ARMOR_ELEMENT_EARTH
    ArmorElementFire,  // SC_ARMOR_ELEMENT_FIRE
    ArmorElementWind,  // SC_ARMOR_ELEMENT_WIND
    Dailysendmailcnt,  // SC_DAILYSENDMAILCNT
    DoramBuf01,  // SC_DORAM_BUF_01
    DoramBuf02,  // SC_DORAM_BUF_02
    Hiss,  // SC_HISS
    Nyanggrass,  // SC_NYANGGRASS
    Grooming,  // SC_GROOMING
    Shrimpblessing,  // SC_SHRIMPBLESSING
    Chattering,  // SC_CHATTERING
    DoramWalkspeed,  // SC_DORAM_WALKSPEED
    DoramMatk,  // SC_DORAM_MATK
    DoramFlee2,  // SC_DORAM_FLEE2
    DoramSvsp,  // SC_DORAM_SVSP
    FallenAngel,  // SC_FALLEN_ANGEL
    Cheerup,  // SC_CHEERUP
    Dressup,  // SC_DRESSUP
    GlastheimAtk,  // SC_GLASTHEIM_ATK
    GlastheimDef,  // SC_GLASTHEIM_DEF
    GlastheimHeal,  // SC_GLASTHEIM_HEAL
    GlastheimHidden,  // SC_GLASTHEIM_HIDDEN
    GlastheimState,  // SC_GLASTHEIM_STATE
    GlastheimItemdef,  // SC_GLASTHEIM_ITEMDEF
    GlastheimHpsp,  // SC_GLASTHEIM_HPSP
    LhzDunN1,  // SC_LHZ_DUN_N1
    LhzDunN2,  // SC_LHZ_DUN_N2
    LhzDunN3,  // SC_LHZ_DUN_N3
    LhzDunN4,  // SC_LHZ_DUN_N4
    Ancilla,  // SC_ANCILLA
    Earthshaker,  // SC_EARTHSHAKER
    WeaponblockOn,  // SC_WEAPONBLOCK_ON
    SporeExplosion,  // SC_SPORE_EXPLOSION
    Adaptation,  // SC_ADAPTATION
    BasilicaCell,  // SC_BASILICA_CELL
    EntryQueueApplyDelay,  // SC_ENTRY_QUEUE_APPLY_DELAY
    EntryQueueNotifyAdmissionTimeOut,  // SC_ENTRY_QUEUE_NOTIFY_ADMISSION_TIME_OUT
    Lightofmoon,  // SC_LIGHTOFMOON
    Lightofsun,  // SC_LIGHTOFSUN
    Lightofstar,  // SC_LIGHTOFSTAR
    Lunarstance,  // SC_LUNARSTANCE
    Universestance,  // SC_UNIVERSESTANCE
    Sunstance,  // SC_SUNSTANCE
    Flashkick,  // SC_FLASHKICK
    Newmoon,  // SC_NEWMOON
    Starstance,  // SC_STARSTANCE
    Dimension,  // SC_DIMENSION
    Dimension1,  // SC_DIMENSION1
    Dimension2,  // SC_DIMENSION2
    Creatingstar,  // SC_CREATINGSTAR
    Fallingstar,  // SC_FALLINGSTAR
    Novaexplosing,  // SC_NOVAEXPLOSING
    Gravitycontrol,  // SC_GRAVITYCONTROL
    Soulcollect,  // SC_SOULCOLLECT
    Soulreaper,  // SC_SOULREAPER
    Soulunity,  // SC_SOULUNITY
    Soulshadow,  // SC_SOULSHADOW
    Soulfairy,  // SC_SOULFAIRY
    Soulfalcon,  // SC_SOULFALCON
    Soulgolem,  // SC_SOULGOLEM
    Souldivision,  // SC_SOULDIVISION
    Soulenergy,  // SC_SOULENERGY
    UseSkillSpSpa,  // SC_USE_SKILL_SP_SPA
    UseSkillSpSha,  // SC_USE_SKILL_SP_SHA
    SpSha,  // SC_SP_SHA
    Soulcurse,  // SC_SOULCURSE
    HellsPlant,  // SC_HELLS_PLANT
    IncreaseMaxhp,  // SC_INCREASE_MAXHP
    IncreaseMaxsp,  // SC_INCREASE_MAXSP
    RefTPotion,  // SC_REF_T_POTION
    AddAtkDamage,  // SC_ADD_ATK_DAMAGE
    AddMatkDamage,  // SC_ADD_MATK_DAMAGE
    Helpangel,  // SC_HELPANGEL
    Soundofdestruction,  // SC_SOUNDOFDESTRUCTION
    Luxanima,  // SC_LUXANIMA
    ReuseLimitLuxanima,  // SC_REUSE_LIMIT_LUXANIMA
    Ensemblefatigue,  // SC_ENSEMBLEFATIGUE
    MistyFrost,  // SC_MISTY_FROST
    MagicPoison,  // SC_MAGIC_POISON
    Ep162BuffSs,  // SC_EP16_2_BUFF_SS
    Ep162BuffSc,  // SC_EP16_2_BUFF_SC
    Ep162BuffAc,  // SC_EP16_2_BUFF_AC
    Overbrandready,  // SC_OVERBRANDREADY
    PoisonMist,  // SC_POISON_MIST
    StoneWall,  // SC_STONE_WALL
    CloudPoison,  // SC_CLOUD_POISON
    HomunTime,  // SC_HOMUN_TIME
    EmergencyMove,  // SC_EMERGENCY_MOVE
    Madogear,  // SC_MADOGEAR
    NpcHallucinationwalk,  // SC_NPC_HALLUCINATIONWALK
    PackingEnvelope1,  // SC_PACKING_ENVELOPE1
    PackingEnvelope2,  // SC_PACKING_ENVELOPE2
    PackingEnvelope3,  // SC_PACKING_ENVELOPE3
    PackingEnvelope4,  // SC_PACKING_ENVELOPE4
    PackingEnvelope5,  // SC_PACKING_ENVELOPE5
    PackingEnvelope6,  // SC_PACKING_ENVELOPE6
    PackingEnvelope7,  // SC_PACKING_ENVELOPE7
    PackingEnvelope8,  // SC_PACKING_ENVELOPE8
    PackingEnvelope9,  // SC_PACKING_ENVELOPE9
    PackingEnvelope10,  // SC_PACKING_ENVELOPE10
    Soulattack,  // SC_SOULATTACK
    Wideweb,  // SC_WIDEWEB
    Burnt,  // SC_BURNT
    Chill,  // SC_CHILL
    HandicapstateDeepblind,  // SC_HANDICAPSTATE_DEEPBLIND
    HandicapstateDeepsilence,  // SC_HANDICAPSTATE_DEEPSILENCE
    HandicapstateLassitude,  // SC_HANDICAPSTATE_LASSITUDE
    HandicapstateFrostbite,  // SC_HANDICAPSTATE_FROSTBITE
    HandicapstateSwooning,  // SC_HANDICAPSTATE_SWOONING
    HandicapstateLightningstrike,  // SC_HANDICAPSTATE_LIGHTNINGSTRIKE
    HandicapstateCrystallization,  // SC_HANDICAPSTATE_CRYSTALLIZATION
    HandicapstateConflagration,  // SC_HANDICAPSTATE_CONFLAGRATION
    HandicapstateMisfortune,  // SC_HANDICAPSTATE_MISFORTUNE
    HandicapstateDeadlypoison,  // SC_HANDICAPSTATE_DEADLYPOISON
    HandicapstateDepression,  // SC_HANDICAPSTATE_DEPRESSION
    HandicapstateHolyflame,  // SC_HANDICAPSTATE_HOLYFLAME
    Servantweapon,  // SC_SERVANTWEAPON
    ServantSign,  // SC_SERVANT_SIGN
    Chargingpierce,  // SC_CHARGINGPIERCE
    ChargingpierceCount,  // SC_CHARGINGPIERCE_COUNT
    DragonicAura,  // SC_DRAGONIC_AURA
    Vigor,  // SC_VIGOR
    DeadlyDefeasance,  // SC_DEADLY_DEFEASANCE
    ClimaxDesHu,  // SC_CLIMAX_DES_HU
    Climax,  // SC_CLIMAX
    ClimaxEarth,  // SC_CLIMAX_EARTH
    ClimaxBloom,  // SC_CLIMAX_BLOOM
    ClimaxCryimp,  // SC_CLIMAX_CRYIMP
    Windsign,  // SC_WINDSIGN
    Crescivebolt,  // SC_CRESCIVEBOLT
    Calamitygale,  // SC_CALAMITYGALE
    Mediale,  // SC_MEDIALE
    AVita,  // SC_A_VITA
    ATelum,  // SC_A_TELUM
    PreAcies,  // SC_PRE_ACIES
    Competentia,  // SC_COMPETENTIA
    Religio,  // SC_RELIGIO
    Benedictum,  // SC_BENEDICTUM
    AxeStomp,  // SC_AXE_STOMP
    AMachine,  // SC_A_MACHINE
    DMachine,  // SC_D_MACHINE
    AbrBattleWarior,  // SC_ABR_BATTLE_WARIOR
    AbrDualCannon,  // SC_ABR_DUAL_CANNON
    AbrMotherNet,  // SC_ABR_MOTHER_NET
    AbrInfinity,  // SC_ABR_INFINITY
    ShadowExceed,  // SC_SHADOW_EXCEED
    DancingKnife,  // SC_DANCING_KNIFE
    PotentVenom,  // SC_POTENT_VENOM
    ShadowScar,  // SC_SHADOW_SCAR
    ESlashCount,  // SC_E_SLASH_COUNT
    ShadowWeapon,  // SC_SHADOW_WEAPON
    GuardStance,  // SC_GUARD_STANCE
    AttackStance,  // SC_ATTACK_STANCE
    GuardianS,  // SC_GUARDIAN_S
    ReboundS,  // SC_REBOUND_S
    HolyS,  // SC_HOLY_S
    UltimateS,  // SC_ULTIMATE_S
    SpearScar,  // SC_SPEAR_SCAR
    ShieldPower,  // SC_SHIELD_POWER
    SpellEnchanting,  // SC_SPELL_ENCHANTING
    SummonElementalArdor,  // SC_SUMMON_ELEMENTAL_ARDOR
    SummonElementalDiluvio,  // SC_SUMMON_ELEMENTAL_DILUVIO
    SummonElementalProcella,  // SC_SUMMON_ELEMENTAL_PROCELLA
    SummonElementalTerremotus,  // SC_SUMMON_ELEMENTAL_TERREMOTUS
    SummonElementalSerpens,  // SC_SUMMON_ELEMENTAL_SERPENS
    ElementalVeil,  // SC_ELEMENTAL_VEIL
    MysticSymphony,  // SC_MYSTIC_SYMPHONY
    KvasirSonata,  // SC_KVASIR_SONATA
    Soundblend,  // SC_SOUNDBLEND
    GefNocturn,  // SC_GEF_NOCTURN
    AinRhapsody,  // SC_AIN_RHAPSODY
    MusicalInterlude,  // SC_MUSICAL_INTERLUDE
    JawaiiSerenade,  // SC_JAWAII_SERENADE
    PronMarch,  // SC_PRON_MARCH
    Roseblossom,  // SC_ROSEBLOSSOM
    PowerfulFaith,  // SC_POWERFUL_FAITH
    SincereFaith,  // SC_SINCERE_FAITH
    FirmFaith,  // SC_FIRM_FAITH
    HolyOil,  // SC_HOLY_OIL
    FirstBrand,  // SC_FIRST_BRAND
    SecondBrand,  // SC_SECOND_BRAND
    SecondJudge,  // SC_SECOND_JUDGE
    ThirdExorFlame,  // SC_THIRD_EXOR_FLAME
    FirstFaithPower,  // SC_FIRST_FAITH_POWER
    MassiveFBlaster,  // SC_MASSIVE_F_BLASTER
    Protectshadowequip,  // SC_PROTECTSHADOWEQUIP
    Researchreport,  // SC_RESEARCHREPORT
    BoHellDusty,  // SC_BO_HELL_DUSTY
    BionicWoodenwarrior,  // SC_BIONIC_WOODENWARRIOR
    BionicWoodenFairy,  // SC_BIONIC_WOODEN_FAIRY
    BionicCreeper,  // SC_BIONIC_CREEPER
    BionicHelltree,  // SC_BIONIC_HELLTREE
    ShadowStrip,  // SC_SHADOW_STRIP
    AbyssDagger,  // SC_ABYSS_DAGGER
    Abyssforceweapon,  // SC_ABYSSFORCEWEAPON
    AbyssSlayer,  // SC_ABYSS_SLAYER
    Flametechnic,  // SC_FLAMETECHNIC
    FlametechnicOption,  // SC_FLAMETECHNIC_OPTION
    Flamearmor,  // SC_FLAMEARMOR
    FlamearmorOption,  // SC_FLAMEARMOR_OPTION
    ColdForce,  // SC_COLD_FORCE
    ColdForceOption,  // SC_COLD_FORCE_OPTION
    CrystalArmor,  // SC_CRYSTAL_ARMOR
    CrystalArmorOption,  // SC_CRYSTAL_ARMOR_OPTION
    GraceBreeze,  // SC_GRACE_BREEZE
    GraceBreezeOption,  // SC_GRACE_BREEZE_OPTION
    EyesOfStorm,  // SC_EYES_OF_STORM
    EyesOfStormOption,  // SC_EYES_OF_STORM_OPTION
    EarthCare,  // SC_EARTH_CARE
    EarthCareOption,  // SC_EARTH_CARE_OPTION
    StrongProtection,  // SC_STRONG_PROTECTION
    StrongProtectionOption,  // SC_STRONG_PROTECTION_OPTION
    DeepPoisoning,  // SC_DEEP_POISONING
    DeepPoisoningOption,  // SC_DEEP_POISONING_OPTION
    PoisonShield,  // SC_POISON_SHIELD
    PoisonShieldOption,  // SC_POISON_SHIELD_OPTION
    SubWeaponproperty,  // SC_SUB_WEAPONPROPERTY
    MLifepotion,  // SC_M_LIFEPOTION
    SManapotion,  // SC_S_MANAPOTION
    Almighty,  // SC_ALMIGHTY
    Ultimatecook,  // SC_ULTIMATECOOK
    MDefscroll,  // SC_M_DEFSCROLL
    InfinityDrink,  // SC_INFINITY_DRINK
    MentalPotion,  // SC_MENTAL_POTION
    LimitPowerBooster,  // SC_LIMIT_POWER_BOOSTER
    CombatPill,  // SC_COMBAT_PILL
    CombatPill2,  // SC_COMBAT_PILL2
    Mysticpowder,  // SC_MYSTICPOWDER
    Sparkcandy,  // SC_SPARKCANDY
    Magiccandy,  // SC_MAGICCANDY
    Acaraje,  // SC_ACARAJE
    Popecookie,  // SC_POPECOOKIE
    VitalizePotion,  // SC_VITALIZE_POTION
    CupOfBoza,  // SC_CUP_OF_BOZA
    SkfMatk,  // SC_SKF_MATK
    SkfAtk,  // SC_SKF_ATK
    SkfAspd,  // SC_SKF_ASPD
    SkfCast,  // SC_SKF_CAST
    BeefRibStew,  // SC_BEEF_RIB_STEW
    PorkRibStew,  // SC_PORK_RIB_STEW
    Weaponbreaker,  // SC_WEAPONBREAKER
    ToxinOfMandara,  // SC_TOXIN_OF_MANDARA
    GoldeneTone,  // SC_GOLDENE_TONE
    Tempering,  // SC_TEMPERING
    GradualGravity,  // SC_GRADUAL_GRAVITY
    AllStatDown,  // SC_ALL_STAT_DOWN
    KillingAura,  // SC_KILLING_AURA
    DamageHeal,  // SC_DAMAGE_HEAL
    ImmunePropertyNothing,  // SC_IMMUNE_PROPERTY_NOTHING
    ImmunePropertyWater,  // SC_IMMUNE_PROPERTY_WATER
    ImmunePropertyGround,  // SC_IMMUNE_PROPERTY_GROUND
    ImmunePropertyFire,  // SC_IMMUNE_PROPERTY_FIRE
    ImmunePropertyWind,  // SC_IMMUNE_PROPERTY_WIND
    ImmunePropertyPoison,  // SC_IMMUNE_PROPERTY_POISON
    ImmunePropertySaint,  // SC_IMMUNE_PROPERTY_SAINT
    ImmunePropertyDarkness,  // SC_IMMUNE_PROPERTY_DARKNESS
    ImmunePropertyTelekinesis,  // SC_IMMUNE_PROPERTY_TELEKINESIS
    ImmunePropertyUndead,  // SC_IMMUNE_PROPERTY_UNDEAD
    RelieveOn,  // SC_RELIEVE_ON
    RelieveOff,  // SC_RELIEVE_OFF
    RushQuake1,  // SC_RUSH_QUAKE1
    RushQuake2,  // SC_RUSH_QUAKE2
    GLifepotion,  // SC_G_LIFEPOTION
    Hnnoweapon,  // SC_HNNOWEAPON
    Shieldchainrush,  // SC_SHIELDCHAINRUSH
    Mistyfrost,  // SC_MISTYFROST
    Groundgravity,  // SC_GROUNDGRAVITY
    Breakinglimit,  // SC_BREAKINGLIMIT
    Rulebreak,  // SC_RULEBREAK
    IntensiveAim,  // SC_INTENSIVE_AIM
    IntensiveAimCount,  // SC_INTENSIVE_AIM_COUNT
    GrenadeFragment1,  // SC_GRENADE_FRAGMENT_1
    GrenadeFragment2,  // SC_GRENADE_FRAGMENT_2
    GrenadeFragment3,  // SC_GRENADE_FRAGMENT_3
    GrenadeFragment4,  // SC_GRENADE_FRAGMENT_4
    GrenadeFragment5,  // SC_GRENADE_FRAGMENT_5
    GrenadeFragment6,  // SC_GRENADE_FRAGMENT_6
    AutoFiringLauncher,  // SC_AUTO_FIRING_LAUNCHER
    HiddenCard,  // SC_HIDDEN_CARD
    PeriodReceiveitem2nd,  // SC_PERIOD_RECEIVEITEM_2ND
    PeriodPlusexp2nd,  // SC_PERIOD_PLUSEXP_2ND
    Powerup = 951,  // SC_POWERUP
    Agiup,  // SC_AGIUP
    Protection,  // SC_PROTECTION
    BathFoamA,  // SC_BATH_FOAM_A
    BathFoamB,  // SC_BATH_FOAM_B
    BathFoamC,  // SC_BATH_FOAM_C
    Buchedenoel,  // SC_BUCHEDENOEL
    Ep16Def,  // SC_EP16_DEF
    StrScroll,  // SC_STR_SCROLL
    IntScroll,  // SC_INT_SCROLL
    Contents1,  // SC_CONTENTS_1
    Contents2,  // SC_CONTENTS_2
    Contents3,  // SC_CONTENTS_3
    Contents4,  // SC_CONTENTS_4
    Contents5,  // SC_CONTENTS_5
    Contents6,  // SC_CONTENTS_6
    Contents7,  // SC_CONTENTS_7
    Contents8,  // SC_CONTENTS_8
    Contents9,  // SC_CONTENTS_9
    Contents10,  // SC_CONTENTS_10
    MysteryPowder,  // SC_MYSTERY_POWDER
    Contents26,  // SC_CONTENTS_26
    Contents27,  // SC_CONTENTS_27
    Contents28,  // SC_CONTENTS_28
    Contents29,  // SC_CONTENTS_29
    Contents31,  // SC_CONTENTS_31
    Contents32,  // SC_CONTENTS_32
    Contents33,  // SC_CONTENTS_33
    TalismanOfProtection,  // SC_TALISMAN_OF_PROTECTION
    TalismanOfWarrior,  // SC_TALISMAN_OF_WARRIOR
    TalismanOfMagician,  // SC_TALISMAN_OF_MAGICIAN
    TalismanOfFiveElements,  // SC_TALISMAN_OF_FIVE_ELEMENTS
    TFirstGod,  // SC_T_FIRST_GOD
    TSecondGod,  // SC_T_SECOND_GOD
    TThirdGod,  // SC_T_THIRD_GOD
    TFourthGod,  // SC_T_FOURTH_GOD
    TFifthGod,  // SC_T_FIFTH_GOD
    HeavenAndEarth,  // SC_HEAVEN_AND_EARTH
    TotemOfTutelary,  // SC_TOTEM_OF_TUTELARY
    ReturnToEldicastes,  // SC_RETURN_TO_ELDICASTES
    GuardianRecall,  // SC_GUARDIAN_RECALL
    EclageRecall,  // SC_ECLAGE_RECALL
    AllNiflheimRecall,  // SC_ALL_NIFLHEIM_RECALL
    AllPronteraRecall,  // SC_ALL_PRONTERA_RECALL
    AllGlastheimRecall,  // SC_ALL_GLASTHEIM_RECALL
    AllThanatosRecall,  // SC_ALL_THANATOS_RECALL
    AllLighthalzenRecall,  // SC_ALL_LIGHTHALZEN_RECALL
    Hogogong,  // SC_HOGOGONG
    MarineFestival,  // SC_MARINE_FESTIVAL
    SandyFestival,  // SC_SANDY_FESTIVAL
    KiSulRampage,  // SC_KI_SUL_RAMPAGE
    ColorsOfHyunRok1,  // SC_COLORS_OF_HYUN_ROK_1
    ColorsOfHyunRok2,  // SC_COLORS_OF_HYUN_ROK_2
    ColorsOfHyunRok3,  // SC_COLORS_OF_HYUN_ROK_3
    ColorsOfHyunRok4,  // SC_COLORS_OF_HYUN_ROK_4
    ColorsOfHyunRok5,  // SC_COLORS_OF_HYUN_ROK_5
    ColorsOfHyunRok6,  // SC_COLORS_OF_HYUN_ROK_6
    ColorsOfHyunRokBuff,  // SC_COLORS_OF_HYUN_ROK_BUFF
    TemporaryCommunion,  // SC_TEMPORARY_COMMUNION
    BlessingOfMCreatures,  // SC_BLESSING_OF_M_CREATURES
    BlessingOfMCDebuff,  // SC_BLESSING_OF_M_C_DEBUFF
    RisingSun,  // SC_RISING_SUN
    NoonSun,  // SC_NOON_SUN
    SunsetSun,  // SC_SUNSET_SUN
    RisingMoon,  // SC_RISING_MOON
    MidnightMoon,  // SC_MIDNIGHT_MOON
    DawnMoon,  // SC_DAWN_MOON
    StarBurst,  // SC_STAR_BURST
    SkyEnchant,  // SC_SKY_ENCHANT
    WildWalk,  // SC_WILD_WALK
    ShadowClock,  // SC_SHADOW_CLOCK
    ShinkirouCall,  // SC_SHINKIROU_CALL
    Nightmare,  // SC_NIGHTMARE
    Sbunshin,  // SC_SBUNSHIN
    // ---- C# port-specific anchors (outside the rAthena range) ----
    // These existed before T2.4a and don't correspond to any rAthena
    // SC; they're parked at high ids so they don't collide with any
    // future rAthena import.

    /// <summary>Generic heal-over-time anchor used by skills/items.
    /// No rAthena counterpart — kept for pre-T2.4 behavior.</summary>
    HealOverTime = 2000,
}
