namespace Core.Database.Entities;

/// <summary>
/// Static skill catalog row — mirror of rAthena's <c>skill_db</c> SQL
/// table (the <c>use_sql_db: yes</c> path of <c>conf/inter_athena.conf</c>).
/// Columns trimmed to what the <c>Map.Server.Skills.SkillDefinition</c>
/// runtime reads today; per-level fields are stored as <c>:</c>-delimited
/// strings (matching the rAthena CSV-style packed schema) and parsed at
/// load time.
///
/// The full catalog (rAthena db/re/skill_db.yml, ~1600 rows) is seeded by
/// <c>seed_skill_db.sql</c> (generated by <c>Tools.RathenaImporter</c>) and loaded into
/// <c>SkillDb</c> via <c>SkillDbLoader.FromEntity</c>; the hand-built starter catalog is the
/// DB-empty fallback. COMBAT-92 added the Requirements / Flags / Unit columns below.
/// </summary>
public class SkillDbEntity
{
    public ushort Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public byte MaxLevel { get; set; }
    public string TargetMode { get; set; } = "Self";         // SelfOnly / TargetEnemy / TargetFriend / Ground / Passive
    public string DamageKind { get; set; } = "None";          // None / Weapon / Magic / Misc / Heal
    public int Range { get; set; } = 1;
    public string Element { get; set; } = "Neutral";

    /// <summary>Status effect applied by buff/debuff skills. Empty = none.</summary>
    public string StatusType { get; set; } = "None";

    /// <summary>Colon-delimited per-level SP cost ("10:12:14:..."). Empty entries default to 0.</summary>
    public string SpCost { get; set; } = string.Empty;
    public string CastTimeMs { get; set; } = string.Empty;
    public string CooldownMs { get; set; } = string.Empty;
    public string DamageRate { get; set; } = string.Empty;
    public string EffectAmount { get; set; } = string.Empty;
    public string StatusDurationMs { get; set; } = string.Empty;

    // COMBAT-92 — rAthena Requirements / Flags / Unit blocks (db/re/skill_db.yml). Stored as
    // string tokens (pipe-delimited names) so the importer stays decoupled from the runtime
    // enum bit-values; SkillDbLoader.FromEntity parses them. Replaces the curated overlays
    // (CuratedAmmo / CuratedInf2 / CuratedUnitFlags) that previously patched these post-load.

    /// <summary>Requirements.Ammo type names, pipe-delimited (e.g. "Arrow", "Bullet|Shell|Grenade").
    /// Empty = no ammo requirement. Only emitted when AmmoAmount &gt; 0 (matches skill_get_ammo_qty
    /// usage — a type with no amount falls through to the weapon-ammo heuristic).</summary>
    public string Ammo { get; set; } = string.Empty;

    /// <summary>Requirements.AmmoAmount (rounds per cast). 0 = none. Renewal skill_db uses the same
    /// amount for every level, so a single int (broadcast across levels) is faithful.</summary>
    public int AmmoAmount { get; set; }

    /// <summary>Flags block — INF2_* names, pipe-delimited (e.g. "IgnoreGvgReduction|IgnoreBgReduction").
    /// FromEntity keeps only the names that map to a known <c>SkillInf2</c> member.</summary>
    public string Inf2 { get; set; } = string.Empty;

    /// <summary>Unit.Flag block — UF_* names, pipe-delimited (e.g. "NoEnemy|NoReiteration").
    /// FromEntity keeps only the names that map to a known <c>SkillUnitFlag</c> member.</summary>
    public string UnitFlags { get; set; } = string.Empty;
}
