// Auto-generated by scripts/tools/import_rathena.py. Do not edit by
// hand — re-run the importer to refresh. Imports every sibling .ts
// file in this directory plus every sub-directory's index.

import "./eden_iro";
