// Auto-generated by scripts/tools/import_rathena.py. Do not edit by
// hand — re-run the importer to refresh. Imports every sibling .ts
// file in this directory plus every sub-directory's index.

import "./bif_fild";
import "./com_fild";
import "./dic_fild";
import "./geffen_fild";
import "./gw_fild";
import "./hugel_fild";
import "./morroc_fild";
import "./payon_fild";
import "./prontera_fild";
import "./rachel_fild";
import "./rockridge_fild";
import "./veins_fild";
import "./yuno_fild";
