// Auto-generated by scripts/tools/import_rathena.py. Do not edit by
// hand — re-run the importer to refresh. Imports every sibling .ts
// file in this directory plus every sub-directory's index.

import "./amatsu";
import "./ayothaya";
import "./ba_lost";
import "./ba_maison";
import "./bifrost";
import "./comodo";
import "./dewata";
import "./dicastes";
import "./eclage";
import "./einbroch";
import "./geffen";
import "./gonryun";
import "./hugel";
import "./lighthalzen";
import "./louyang";
import "./lutie";
import "./malaya";
import "./manuk";
import "./mjolnir";
import "./morocc";
import "./moscovia";
import "./niflheim";
import "./payon";
import "./prontera";
import "./rachel";
import "./rockridge";
import "./splendide";
import "./umbala";
import "./veins";
import "./yuno";
