using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Tools.RathenaImporter;

/// <summary>
/// Turn a parsed rAthena .conf into:
/// <list type="bullet">
///   <item>A <c>.json</c> file with values + a <c>$schema</c> reference.</item>
///   <item>A companion <c>.schema.json</c> (JSON Schema draft-2020-12)
///         where each property carries a <c>description</c> sourced
///         from the .conf comments — gives autocomplete in VS Code,
///         Rider, and VS 2022.</item>
/// </list>
///
/// Values are type-inferred:
/// <list type="bullet">
///   <item><c>0xFF</c> / <c>0xDeadBeef</c> → number (hex).</item>
///   <item><c>123</c> → number.</item>
///   <item><c>yes</c> / <c>no</c> / <c>true</c> / <c>false</c> → boolean.</item>
///   <item>Everything else → string.</item>
/// </list>
/// </summary>
public static class ConfToJsonConverter
{
    public sealed record Result(string Json, string Schema, int PropertyCount);

    public static Result Convert(ConfParser.ConfKey root, string title, string schemaUri)
    {
        var data = new JsonObject();
        data["$schema"] = schemaUri;
        var schema = new JsonObject
        {
            ["$schema"] = "https://json-schema.org/draft/2020-12/schema",
            ["$id"] = schemaUri,
            ["title"] = title,
            ["description"] = $"Generated by Tools.RathenaImporter from rAthena .conf. Each property's description is the inline comment from the source file.",
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject(),
        };
        var count = WriteBlock(root, (JsonObject)data, (JsonObject)schema["properties"]!);
        return new Result(
            JsonSerializer.Serialize(data, new JsonSerializerOptions { WriteIndented = true }),
            JsonSerializer.Serialize(schema, new JsonSerializerOptions { WriteIndented = true }),
            count);
    }

    private static int WriteBlock(ConfParser.ConfKey block, JsonObject data, JsonObject props)
    {
        var count = 0;
        foreach (var k in block.Children)
        {
            if (k.Children.Count > 0)
            {
                // nested object
                var nested = new JsonObject();
                var nestedProps = new JsonObject();
                var nestedSchema = new JsonObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = false,
                    ["properties"] = nestedProps,
                };
                if (!string.IsNullOrEmpty(k.Description))
                    nestedSchema["description"] = k.Description!;
                count += WriteBlock(k, nested, nestedProps);
                data[k.Name] = nested;
                props[k.Name] = nestedSchema;
            }
            else if (k.Value != null)
            {
                var (jsonValue, jsonType) = InferType(k.Value);
                data[k.Name] = jsonValue;
                var sch = new JsonObject { ["type"] = jsonType };
                if (!string.IsNullOrEmpty(k.Description))
                    sch["description"] = k.Description!;
                // record the original raw value as `default` so the
                // schema documents rAthena's shipping value.
                sch["default"] = jsonValue?.DeepClone();
                props[k.Name] = sch;
                count++;
            }
        }
        return count;
    }

    private static (JsonNode? value, string type) InferType(string raw)
    {
        var trimmed = raw.Trim();
        if (trimmed.Equals("true", StringComparison.OrdinalIgnoreCase) ||
            trimmed.Equals("yes", StringComparison.OrdinalIgnoreCase))
            return (JsonValue.Create(true), "boolean");
        if (trimmed.Equals("false", StringComparison.OrdinalIgnoreCase) ||
            trimmed.Equals("no", StringComparison.OrdinalIgnoreCase))
            return (JsonValue.Create(false), "boolean");
        if (trimmed.StartsWith("0x", StringComparison.OrdinalIgnoreCase) &&
            long.TryParse(trimmed.AsSpan(2), System.Globalization.NumberStyles.HexNumber,
                System.Globalization.CultureInfo.InvariantCulture, out var hex))
            return (JsonValue.Create(hex), "integer");
        if (long.TryParse(trimmed, System.Globalization.NumberStyles.Integer,
                System.Globalization.CultureInfo.InvariantCulture, out var i))
            return (JsonValue.Create(i), "integer");
        if (double.TryParse(trimmed, System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var d))
            return (JsonValue.Create(d), "number");
        return (JsonValue.Create(trimmed), "string");
    }
}
