using System.Globalization;
using System.Text;

namespace Tools.RathenaImporter;

/// <summary>
/// Shared SQL emission helpers — REPLACE-statement builders +
/// MySQL string escaping. Every converter funnels through these so
/// the output stays consistent.
/// </summary>
internal static class SqlEmit
{
    /// <summary>
    /// Escape a string for a single-quoted MySQL string literal.
    /// Doubles single quotes; preserves UTF-8.
    /// </summary>
    public static string Esc(string? s) => s == null ? "" : s.Replace("\\", "\\\\").Replace("'", "''");

    /// <summary>Format a value into the SQL VALUE position. null → NULL.</summary>
    public static string V(object? value)
    {
        if (value == null) return "NULL";
        return value switch
        {
            bool b => b ? "1" : "0",
            string s => $"'{Esc(s)}'",
            int i => i.ToString(CultureInfo.InvariantCulture),
            long l => l.ToString(CultureInfo.InvariantCulture),
            short sh => sh.ToString(CultureInfo.InvariantCulture),
            byte by => by.ToString(CultureInfo.InvariantCulture),
            uint ui => ui.ToString(CultureInfo.InvariantCulture),
            ulong ul => ul.ToString(CultureInfo.InvariantCulture),
            ushort ush => ush.ToString(CultureInfo.InvariantCulture),
            double d => d.ToString(CultureInfo.InvariantCulture),
            _ => $"'{Esc(value.ToString())}'",
        };
    }

    /// <summary>
    /// Emit a REPLACE INTO `table` (col1,col2,...) VALUES (v1,v2,...);
    /// Both lists must have the same length.
    /// </summary>
    public static string Replace(string table, IReadOnlyList<string> columns, IReadOnlyList<object?> values)
    {
        if (columns.Count != values.Count)
            throw new ArgumentException($"column count ({columns.Count}) ≠ value count ({values.Count})");
        var sb = new StringBuilder();
        sb.Append("REPLACE INTO `").Append(table).Append("` (");
        for (var i = 0; i < columns.Count; i++)
        {
            if (i > 0) sb.Append(',');
            sb.Append('`').Append(columns[i]).Append('`');
        }
        sb.Append(") VALUES (");
        for (var i = 0; i < values.Count; i++)
        {
            if (i > 0) sb.Append(',');
            sb.Append(V(values[i]));
        }
        sb.Append(");");
        return sb.ToString();
    }

    /// <summary>
    /// File header banner. Identifies the generator + source so
    /// hand-edits are obvious.
    /// </summary>
    public static string Header(string converterName, string sourcePath, int rowCount)
        => $"-- Auto-generated by Tools.RathenaImporter ({converterName}).\n" +
           $"-- Source: {sourcePath}\n" +
           $"-- Rows: {rowCount}\n" +
           $"-- Do not edit by hand — re-run `dotnet run --project Tools.RathenaImporter`.\n\n";
}
