using System.Text;

namespace Tools.RathenaImporter;

/// <summary>
/// Writes INSERT statements in batches. Big seed files insert tens of
/// thousands of rows; using multi-row INSERTs keeps both the SQL file
/// size and the MariaDB ingest time reasonable.
/// </summary>
public static class SqlWriter
{
    private const int BatchSize = 500;

    public static void WriteWarps(string path, IReadOnlyList<WarpRow> rows)
    {
        using var w = new StreamWriter(path, append: false, Encoding.UTF8);
        WriteHeader(w, "warp", rows.Count);
        w.WriteLine("DELETE FROM `warp`;");
        WriteBatched(w, rows, BatchSize,
            "INSERT INTO `warp` (`src_map`,`src_x`,`src_y`,`src_dir`,`warp_type`,`name`,`span_xs`,`span_ys`,`dst_map`,`dst_x`,`dst_y`) VALUES",
            r => $"({Q(r.SrcMap)},{r.SrcX},{r.SrcY},{r.SrcDir},{Q(r.WarpType)},{Q(r.Name)},{r.SpanXs},{r.SpanYs},{Q(r.DstMap)},{r.DstX},{r.DstY})");
    }

    public static void WriteMobSpawns(string path, IReadOnlyList<MobSpawnRow> rows)
    {
        using var w = new StreamWriter(path, append: false, Encoding.UTF8);
        WriteHeader(w, "mob_spawn", rows.Count);
        w.WriteLine("DELETE FROM `mob_spawn`;");
        WriteBatched(w, rows, BatchSize,
            "INSERT INTO `mob_spawn` (`map_name`,`center_x`,`center_y`,`span_xs`,`span_ys`,`is_boss`,`display_name`,`mob_id`,`amount`,`delay1`,`delay2`,`event_label`,`size`,`ai`) VALUES",
            r => $"({Q(r.MapName)},{r.CenterX},{r.CenterY},{r.SpanXs},{r.SpanYs},{(r.IsBoss ? 1 : 0)},{Q(r.DisplayName)},{r.MobId},{r.Amount},{r.Delay1},{r.Delay2},{Q(r.EventLabel)},{r.Size},{r.Ai})");
    }

    public static void WriteMapFlags(string path, IReadOnlyList<MapFlagRow> rows)
    {
        using var w = new StreamWriter(path, append: false, Encoding.UTF8);
        WriteHeader(w, "map_flag", rows.Count);
        w.WriteLine("DELETE FROM `map_flag`;");
        WriteBatched(w, rows, BatchSize,
            "INSERT INTO `map_flag` (`map_name`,`flag`,`value`) VALUES",
            r => $"({Q(r.MapName)},{Q(r.Flag)},{Q(r.Value)})");
    }

    private static void WriteHeader(StreamWriter w, string table, int rowCount)
    {
        w.WriteLine($"-- Auto-generated by Tools.RathenaImporter from rAthena npc/re/*.txt");
        w.WriteLine($"-- Table: {table}    Rows: {rowCount}");
        w.WriteLine($"-- Re-run the importer when the rAthena source files change.");
        w.WriteLine();
    }

    private static void WriteBatched<T>(StreamWriter w, IReadOnlyList<T> rows, int batch, string insertPrefix, Func<T, string> rowFmt)
    {
        for (var i = 0; i < rows.Count; i += batch)
        {
            w.WriteLine(insertPrefix);
            var end = Math.Min(i + batch, rows.Count);
            for (var j = i; j < end; j++)
            {
                w.Write("  ");
                w.Write(rowFmt(rows[j]));
                w.WriteLine(j == end - 1 ? ";" : ",");
            }
        }
    }

    /// <summary>SQL string-escape: wrap in single quotes, double any embedded single quotes.</summary>
    private static string Q(string s) => "'" + (s ?? string.Empty).Replace("'", "''") + "'";
}
